/**
 * @file CO_profile_mixed_demo.c
 * @brief Canonical logical-device ownership table for the package mixed demo.
 */

#include "CO_profile_mixed_demo.h"

const CO_profile_descriptor_t CO_profileMixedDemoDescriptors[CO_PROFILE_MIXED_DEMO_DESCRIPTOR_COUNT] = {
    {CO_PROFILE_MIXED_DEMO_CIA402_AXIS0_LOGICAL_DEVICE, CO_PROFILE_MIXED_DEMO_CIA402_PROFILE_NUMBER},
    {CO_PROFILE_MIXED_DEMO_CIA402_AXIS1_LOGICAL_DEVICE, CO_PROFILE_MIXED_DEMO_CIA402_PROFILE_NUMBER},
    {CO_PROFILE_MIXED_DEMO_CIA402_AXIS2_LOGICAL_DEVICE, CO_PROFILE_MIXED_DEMO_CIA402_PROFILE_NUMBER},
    {CO_PROFILE_MIXED_DEMO_CIA401_LOGICAL_DEVICE, CO_PROFILE_MIXED_DEMO_CIA401_PROFILE_NUMBER},
};
