/**
 * @file CO_config_rtt.h
 * @brief RT-Thread Kconfig to CANopenNode CO_CONFIG_* mapping.
 * @details This header maps RT-Thread package Kconfig options to CANopenNode compile-time configuration macros.
 * @author wdfk-prog ()
 * @version 1.0.0
 * @date 2026.07.04
 *
 * @copyright Copyright (c) 2026
 *
 * @note :
 * @par 修改日志:
 * Date       Version Author      Description
 * 2026.07.04 1.0.0   wdfk-prog   first version
 */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef CO_CONFIG_RTT_H_
#define CO_CONFIG_RTT_H_

/* Includes ------------------------------------------------------------------*/

#include <rtthread.h>

/* Exported constants --------------------------------------------------------*/

/* Exported macro ------------------------------------------------------------*/

/*
 * Map RT-Thread Kconfig symbols to CANopenNode CO_CONFIG_* bitmasks.
 * Including rtthread.h only makes PKG_CANOPENNODE_* visible; the stack itself
 * consumes CO_CONFIG_* values, so the mapping must be included by the target header.
 */
#if defined(PKG_CANOPENNODE_USING_MULTIPLE_OD) && !defined(CO_MULTIPLE_OD)
/** Enable CO_new() to use a persistent CO_config_t supplied by the RT-Thread wrapper. */
#define CO_MULTIPLE_OD
#endif /* defined(PKG_CANOPENNODE_USING_MULTIPLE_OD) && !defined(CO_MULTIPLE_OD) */

#if defined(PKG_CANOPENNODE_GLOBAL_CALLBACK_PRE)
#define CO_CONFIG_GLOBAL_FLAG_CALLBACK_PRE CO_CONFIG_FLAG_CALLBACK_PRE
#else
#define CO_CONFIG_GLOBAL_FLAG_CALLBACK_PRE 0
#endif /* defined(PKG_CANOPENNODE_GLOBAL_CALLBACK_PRE) */

#if defined(PKG_CANOPENNODE_GLOBAL_RT_CALLBACK_PRE)
#define CO_CONFIG_GLOBAL_RT_FLAG_CALLBACK_PRE CO_CONFIG_FLAG_CALLBACK_PRE
#else
#define CO_CONFIG_GLOBAL_RT_FLAG_CALLBACK_PRE 0
#endif /* defined(PKG_CANOPENNODE_GLOBAL_RT_CALLBACK_PRE) */

#if defined(PKG_CANOPENNODE_GLOBAL_TIMERNEXT)
#define CO_CONFIG_GLOBAL_FLAG_TIMERNEXT CO_CONFIG_FLAG_TIMERNEXT
#else
#define CO_CONFIG_GLOBAL_FLAG_TIMERNEXT 0
#endif /* defined(PKG_CANOPENNODE_GLOBAL_TIMERNEXT) */

#if defined(PKG_CANOPENNODE_GLOBAL_OD_DYNAMIC)
#define CO_CONFIG_GLOBAL_FLAG_OD_DYNAMIC CO_CONFIG_FLAG_OD_DYNAMIC
#else
#define CO_CONFIG_GLOBAL_FLAG_OD_DYNAMIC 0
#endif /* defined(PKG_CANOPENNODE_GLOBAL_OD_DYNAMIC) */

#if defined(PKG_CANOPENNODE_NMT_CALLBACK_CHANGE)
#define CO_RTT_CONFIG_NMT_CALLBACK_CHANGE CO_CONFIG_NMT_CALLBACK_CHANGE
#else
#define CO_RTT_CONFIG_NMT_CALLBACK_CHANGE 0
#endif /* defined(PKG_CANOPENNODE_NMT_CALLBACK_CHANGE) */
#if defined(PKG_CANOPENNODE_NMT_MASTER)
#define CO_RTT_CONFIG_NMT_MASTER CO_CONFIG_NMT_MASTER
#else
#define CO_RTT_CONFIG_NMT_MASTER 0
#endif /* defined(PKG_CANOPENNODE_NMT_MASTER) */
#ifndef CO_CONFIG_NMT
#define CO_CONFIG_NMT                 (CO_RTT_CONFIG_NMT_CALLBACK_CHANGE \
                                      | CO_RTT_CONFIG_NMT_MASTER \
                                      | CO_CONFIG_GLOBAL_FLAG_CALLBACK_PRE \
                                      | CO_CONFIG_GLOBAL_FLAG_TIMERNEXT)
#endif /* CO_CONFIG_NMT */

#if defined(PKG_CANOPENNODE_USING_HB_CONS)
#if defined(PKG_CANOPENNODE_HB_CONS_CALLBACK_CHANGE)
#define CO_RTT_CONFIG_HB_CONS_CALLBACK_CHANGE CO_CONFIG_HB_CONS_CALLBACK_CHANGE
#else
#define CO_RTT_CONFIG_HB_CONS_CALLBACK_CHANGE 0
#endif /* defined(PKG_CANOPENNODE_HB_CONS_CALLBACK_CHANGE) */
#if defined(PKG_CANOPENNODE_HB_CONS_CALLBACK_MULTI)
#define CO_RTT_CONFIG_HB_CONS_CALLBACK_MULTI CO_CONFIG_HB_CONS_CALLBACK_MULTI
#else
#define CO_RTT_CONFIG_HB_CONS_CALLBACK_MULTI 0
#endif /* defined(PKG_CANOPENNODE_HB_CONS_CALLBACK_MULTI) */
#if defined(PKG_CANOPENNODE_HB_CONS_QUERY_FUNCT)
#define CO_RTT_CONFIG_HB_CONS_QUERY_FUNCT CO_CONFIG_HB_CONS_QUERY_FUNCT
#else
#define CO_RTT_CONFIG_HB_CONS_QUERY_FUNCT 0
#endif /* defined(PKG_CANOPENNODE_HB_CONS_QUERY_FUNCT) */
#define CO_CONFIG_HB_CONS             (CO_CONFIG_HB_CONS_ENABLE \
                                      | CO_RTT_CONFIG_HB_CONS_CALLBACK_CHANGE \
                                      | CO_RTT_CONFIG_HB_CONS_CALLBACK_MULTI \
                                      | CO_RTT_CONFIG_HB_CONS_QUERY_FUNCT \
                                      | CO_CONFIG_GLOBAL_FLAG_CALLBACK_PRE \
                                      | CO_CONFIG_GLOBAL_FLAG_TIMERNEXT \
                                      | CO_CONFIG_GLOBAL_FLAG_OD_DYNAMIC)
#else
#define CO_CONFIG_HB_CONS 0
#endif /* defined(PKG_CANOPENNODE_USING_HB_CONS) */

#if defined(PKG_CANOPENNODE_USING_NODE_GUARDING)
#if defined(PKG_CANOPENNODE_NODE_GUARDING_SLAVE)
#define CO_RTT_CONFIG_NODE_GUARDING_SLAVE CO_CONFIG_NODE_GUARDING_SLAVE_ENABLE
#else
#define CO_RTT_CONFIG_NODE_GUARDING_SLAVE 0
#endif /* defined(PKG_CANOPENNODE_NODE_GUARDING_SLAVE) */
#if defined(PKG_CANOPENNODE_NODE_GUARDING_MASTER)
#define CO_RTT_CONFIG_NODE_GUARDING_MASTER CO_CONFIG_NODE_GUARDING_MASTER_ENABLE
#else
#define CO_RTT_CONFIG_NODE_GUARDING_MASTER 0
#endif /* defined(PKG_CANOPENNODE_NODE_GUARDING_MASTER) */
#define CO_CONFIG_NODE_GUARDING       (CO_RTT_CONFIG_NODE_GUARDING_SLAVE \
                                      | CO_RTT_CONFIG_NODE_GUARDING_MASTER \
                                      | CO_CONFIG_GLOBAL_FLAG_TIMERNEXT)
#else
#define CO_CONFIG_NODE_GUARDING 0
#endif /* defined(PKG_CANOPENNODE_USING_NODE_GUARDING) */
#if defined(PKG_CANOPENNODE_NODE_GUARDING_MASTER_COUNT)
#define CO_CONFIG_NODE_GUARDING_MASTER_COUNT PKG_CANOPENNODE_NODE_GUARDING_MASTER_COUNT
#else
#define CO_CONFIG_NODE_GUARDING_MASTER_COUNT 0x7F
#endif /* defined(PKG_CANOPENNODE_NODE_GUARDING_MASTER_COUNT) */

#if defined(PKG_CANOPENNODE_EM_PRODUCER)
#define CO_RTT_CONFIG_EM_PRODUCER CO_CONFIG_EM_PRODUCER
#else
#define CO_RTT_CONFIG_EM_PRODUCER 0
#endif /* defined(PKG_CANOPENNODE_EM_PRODUCER) */
#if defined(PKG_CANOPENNODE_EM_PROD_CONFIGURABLE)
#define CO_RTT_CONFIG_EM_PROD_CONFIGURABLE CO_CONFIG_EM_PROD_CONFIGURABLE
#else
#define CO_RTT_CONFIG_EM_PROD_CONFIGURABLE 0
#endif /* defined(PKG_CANOPENNODE_EM_PROD_CONFIGURABLE) */
#if defined(PKG_CANOPENNODE_EM_PROD_INHIBIT)
#define CO_RTT_CONFIG_EM_PROD_INHIBIT CO_CONFIG_EM_PROD_INHIBIT
#else
#define CO_RTT_CONFIG_EM_PROD_INHIBIT 0
#endif /* defined(PKG_CANOPENNODE_EM_PROD_INHIBIT) */
#if defined(PKG_CANOPENNODE_EM_HISTORY)
#define CO_RTT_CONFIG_EM_HISTORY CO_CONFIG_EM_HISTORY
#else
#define CO_RTT_CONFIG_EM_HISTORY 0
#endif /* defined(PKG_CANOPENNODE_EM_HISTORY) */
#if defined(PKG_CANOPENNODE_EM_STATUS_BITS)
#define CO_RTT_CONFIG_EM_STATUS_BITS CO_CONFIG_EM_STATUS_BITS
#else
#define CO_RTT_CONFIG_EM_STATUS_BITS 0
#endif /* defined(PKG_CANOPENNODE_EM_STATUS_BITS) */
#if defined(PKG_CANOPENNODE_EM_CONSUMER)
#define CO_RTT_CONFIG_EM_CONSUMER CO_CONFIG_EM_CONSUMER
#else
#define CO_RTT_CONFIG_EM_CONSUMER 0
#endif /* defined(PKG_CANOPENNODE_EM_CONSUMER) */
#define CO_RTT_CONFIG_EM_FEATURES     (CO_RTT_CONFIG_EM_PRODUCER \
                                      | CO_RTT_CONFIG_EM_PROD_CONFIGURABLE \
                                      | CO_RTT_CONFIG_EM_PROD_INHIBIT \
                                      | CO_RTT_CONFIG_EM_HISTORY \
                                      | CO_RTT_CONFIG_EM_STATUS_BITS \
                                      | CO_RTT_CONFIG_EM_CONSUMER)
#define CO_CONFIG_EM                  (CO_RTT_CONFIG_EM_FEATURES \
                                      | CO_CONFIG_GLOBAL_FLAG_CALLBACK_PRE \
                                      | CO_CONFIG_GLOBAL_FLAG_TIMERNEXT)
#if CO_RTT_CONFIG_EM_FEATURES == 0
#error "The RT-Thread wrapper requires CANopenNode Emergency object support. Enable at least one PKG_CANOPENNODE_EM_* feature."
#endif /* CO_RTT_CONFIG_EM_FEATURES == 0 */
#if defined(PKG_CANOPENNODE_EM_ERR_STATUS_BITS_COUNT)
#define CO_CONFIG_EM_ERR_STATUS_BITS_COUNT PKG_CANOPENNODE_EM_ERR_STATUS_BITS_COUNT
#else
#define CO_CONFIG_EM_ERR_STATUS_BITS_COUNT (10 * 8)
#endif /* defined(PKG_CANOPENNODE_EM_ERR_STATUS_BITS_COUNT) */
#define CO_RTT_EM_ERR_STATUS_BITS_COUNT_INVALID \
    ((CO_CONFIG_EM_ERR_STATUS_BITS_COUNT < 48) || (CO_CONFIG_EM_ERR_STATUS_BITS_COUNT > 256) \
     || ((CO_CONFIG_EM_ERR_STATUS_BITS_COUNT % 8) != 0))
#if CO_RTT_EM_ERR_STATUS_BITS_COUNT_INVALID
#error "PKG_CANOPENNODE_EM_ERR_STATUS_BITS_COUNT must be in range 48..256 and increment by 8."
#endif /* CO_RTT_EM_ERR_STATUS_BITS_COUNT_INVALID */
#if defined(PKG_CANOPENNODE_ERR_CONDITION_GENERIC_STACK)
#define CO_CONFIG_ERR_CONDITION_GENERIC (em->errorStatusBits[5] != 0)
#endif /* defined(PKG_CANOPENNODE_ERR_CONDITION_GENERIC_STACK) */
#if defined(PKG_CANOPENNODE_ERR_CONDITION_COMMUNICATION_STACK)
#define CO_CONFIG_ERR_CONDITION_COMMUNICATION (em->errorStatusBits[2] || em->errorStatusBits[3])
#endif /* defined(PKG_CANOPENNODE_ERR_CONDITION_COMMUNICATION_STACK) */
#if defined(PKG_CANOPENNODE_ERR_CONDITION_MANUFACTURER_STACK)
#if CO_CONFIG_EM_ERR_STATUS_BITS_COUNT >= 80
#define CO_CONFIG_ERR_CONDITION_MANUFACTURER (em->errorStatusBits[8] || em->errorStatusBits[9])
#else
#error "PKG_CANOPENNODE_ERR_CONDITION_MANUFACTURER_STACK requires CO_CONFIG_EM_ERR_STATUS_BITS_COUNT >= 80"
#endif /* CO_CONFIG_EM_ERR_STATUS_BITS_COUNT >= 80 */
#endif /* defined(PKG_CANOPENNODE_ERR_CONDITION_MANUFACTURER_STACK) */
#if defined(PKG_CANOPENNODE_ERR_CONDITION_CURRENT_ZERO)
#define CO_CONFIG_ERR_CONDITION_CURRENT 0
#endif /* defined(PKG_CANOPENNODE_ERR_CONDITION_CURRENT_ZERO) */
#if defined(PKG_CANOPENNODE_ERR_CONDITION_VOLTAGE_ZERO)
#define CO_CONFIG_ERR_CONDITION_VOLTAGE 0
#endif /* defined(PKG_CANOPENNODE_ERR_CONDITION_VOLTAGE_ZERO) */
#if defined(PKG_CANOPENNODE_ERR_CONDITION_TEMPERATURE_ZERO)
#define CO_CONFIG_ERR_CONDITION_TEMPERATURE 0
#endif /* defined(PKG_CANOPENNODE_ERR_CONDITION_TEMPERATURE_ZERO) */
#if defined(PKG_CANOPENNODE_ERR_CONDITION_DEV_PROFILE_ZERO)
#define CO_CONFIG_ERR_CONDITION_DEV_PROFILE 0
#endif /* defined(PKG_CANOPENNODE_ERR_CONDITION_DEV_PROFILE_ZERO) */

#if defined(PKG_CANOPENNODE_USING_SDO_SERVER)
#if defined(PKG_CANOPENNODE_SDO_SRV_SEGMENTED)
#define CO_RTT_CONFIG_SDO_SRV_SEGMENTED CO_CONFIG_SDO_SRV_SEGMENTED
#else
#define CO_RTT_CONFIG_SDO_SRV_SEGMENTED 0
#endif /* defined(PKG_CANOPENNODE_SDO_SRV_SEGMENTED) */
#if defined(PKG_CANOPENNODE_SDO_SRV_BLOCK)
#define CO_RTT_CONFIG_SDO_SRV_BLOCK CO_CONFIG_SDO_SRV_BLOCK
#else
#define CO_RTT_CONFIG_SDO_SRV_BLOCK 0
#endif /* defined(PKG_CANOPENNODE_SDO_SRV_BLOCK) */
#define CO_CONFIG_SDO_SRV             (CO_RTT_CONFIG_SDO_SRV_SEGMENTED \
                                      | CO_RTT_CONFIG_SDO_SRV_BLOCK \
                                      | CO_CONFIG_GLOBAL_FLAG_CALLBACK_PRE \
                                      | CO_CONFIG_GLOBAL_FLAG_TIMERNEXT \
                                      | CO_CONFIG_GLOBAL_FLAG_OD_DYNAMIC)
#else
#define CO_CONFIG_SDO_SRV 0
#endif /* defined(PKG_CANOPENNODE_USING_SDO_SERVER) */
#if defined(PKG_CANOPENNODE_SDO_SRV_BUFFER_SIZE)
#define CO_CONFIG_SDO_SRV_BUFFER_SIZE  PKG_CANOPENNODE_SDO_SRV_BUFFER_SIZE
#else
#define CO_CONFIG_SDO_SRV_BUFFER_SIZE  32
#endif /* defined(PKG_CANOPENNODE_SDO_SRV_BUFFER_SIZE) */

#if defined(PKG_CANOPENNODE_USING_SDO_CLIENT)
#if defined(PKG_CANOPENNODE_SDO_CLI_SEGMENTED)
#define CO_RTT_CONFIG_SDO_CLI_SEGMENTED CO_CONFIG_SDO_CLI_SEGMENTED
#else
#define CO_RTT_CONFIG_SDO_CLI_SEGMENTED 0
#endif /* defined(PKG_CANOPENNODE_SDO_CLI_SEGMENTED) */
#if defined(PKG_CANOPENNODE_SDO_CLI_BLOCK)
#define CO_RTT_CONFIG_SDO_CLI_BLOCK CO_CONFIG_SDO_CLI_BLOCK
#else
#define CO_RTT_CONFIG_SDO_CLI_BLOCK 0
#endif /* defined(PKG_CANOPENNODE_SDO_CLI_BLOCK) */
#if defined(PKG_CANOPENNODE_SDO_CLI_LOCAL)
#define CO_RTT_CONFIG_SDO_CLI_LOCAL CO_CONFIG_SDO_CLI_LOCAL
#else
#define CO_RTT_CONFIG_SDO_CLI_LOCAL 0
#endif /* defined(PKG_CANOPENNODE_SDO_CLI_LOCAL) */
#define CO_CONFIG_SDO_CLI             (CO_CONFIG_SDO_CLI_ENABLE \
                                      | CO_RTT_CONFIG_SDO_CLI_SEGMENTED \
                                      | CO_RTT_CONFIG_SDO_CLI_BLOCK \
                                      | CO_RTT_CONFIG_SDO_CLI_LOCAL \
                                      | CO_CONFIG_GLOBAL_FLAG_CALLBACK_PRE \
                                      | CO_CONFIG_GLOBAL_FLAG_TIMERNEXT \
                                      | CO_CONFIG_GLOBAL_FLAG_OD_DYNAMIC)
#else
#define CO_CONFIG_SDO_CLI 0
#endif /* defined(PKG_CANOPENNODE_USING_SDO_CLIENT) */
#if defined(PKG_CANOPENNODE_SDO_CLI_BUFFER_SIZE)
#define CO_CONFIG_SDO_CLI_BUFFER_SIZE  PKG_CANOPENNODE_SDO_CLI_BUFFER_SIZE
#else
#define CO_CONFIG_SDO_CLI_BUFFER_SIZE  32
#endif /* defined(PKG_CANOPENNODE_SDO_CLI_BUFFER_SIZE) */

#if defined(PKG_CANOPENNODE_USING_TIME)
#if defined(PKG_CANOPENNODE_TIME_PRODUCER)
#define CO_RTT_CONFIG_TIME_PRODUCER CO_CONFIG_TIME_PRODUCER
#else
#define CO_RTT_CONFIG_TIME_PRODUCER 0
#endif /* defined(PKG_CANOPENNODE_TIME_PRODUCER) */
#define CO_CONFIG_TIME                (CO_CONFIG_TIME_ENABLE \
                                      | CO_RTT_CONFIG_TIME_PRODUCER \
                                      | CO_CONFIG_GLOBAL_FLAG_CALLBACK_PRE \
                                      | CO_CONFIG_GLOBAL_FLAG_OD_DYNAMIC)
#else
#define CO_CONFIG_TIME 0
#endif /* defined(PKG_CANOPENNODE_USING_TIME) */

#if defined(PKG_CANOPENNODE_USING_SYNC)
#if defined(PKG_CANOPENNODE_SYNC_PRODUCER)
#define CO_RTT_CONFIG_SYNC_PRODUCER CO_CONFIG_SYNC_PRODUCER
#else
#define CO_RTT_CONFIG_SYNC_PRODUCER 0
#endif /* defined(PKG_CANOPENNODE_SYNC_PRODUCER) */
#define CO_CONFIG_SYNC                (CO_CONFIG_SYNC_ENABLE \
                                      | CO_RTT_CONFIG_SYNC_PRODUCER \
                                      | CO_CONFIG_GLOBAL_RT_FLAG_CALLBACK_PRE \
                                      | CO_CONFIG_GLOBAL_FLAG_TIMERNEXT \
                                      | CO_CONFIG_GLOBAL_FLAG_OD_DYNAMIC)
#else
#define CO_CONFIG_SYNC 0
#endif /* defined(PKG_CANOPENNODE_USING_SYNC) */

#if defined(PKG_CANOPENNODE_USING_PDO)
#if defined(PKG_CANOPENNODE_RPDO)
#define CO_RTT_CONFIG_RPDO CO_CONFIG_RPDO_ENABLE
#else
#define CO_RTT_CONFIG_RPDO 0
#endif /* defined(PKG_CANOPENNODE_RPDO) */
#if defined(PKG_CANOPENNODE_TPDO)
#define CO_RTT_CONFIG_TPDO CO_CONFIG_TPDO_ENABLE
#else
#define CO_RTT_CONFIG_TPDO 0
#endif /* defined(PKG_CANOPENNODE_TPDO) */
#if defined(PKG_CANOPENNODE_RPDO_TIMERS)
#define CO_RTT_CONFIG_RPDO_TIMERS CO_CONFIG_RPDO_TIMERS_ENABLE
#else
#define CO_RTT_CONFIG_RPDO_TIMERS 0
#endif /* defined(PKG_CANOPENNODE_RPDO_TIMERS) */
#if defined(PKG_CANOPENNODE_TPDO_TIMERS)
#define CO_RTT_CONFIG_TPDO_TIMERS CO_CONFIG_TPDO_TIMERS_ENABLE
#else
#define CO_RTT_CONFIG_TPDO_TIMERS 0
#endif /* defined(PKG_CANOPENNODE_TPDO_TIMERS) */
#if defined(PKG_CANOPENNODE_PDO_SYNC)
#define CO_RTT_CONFIG_PDO_SYNC CO_CONFIG_PDO_SYNC_ENABLE
#else
#define CO_RTT_CONFIG_PDO_SYNC 0
#endif /* defined(PKG_CANOPENNODE_PDO_SYNC) */
#if defined(PKG_CANOPENNODE_PDO_OD_IO_ACCESS)
#define CO_RTT_CONFIG_PDO_OD_IO_ACCESS CO_CONFIG_PDO_OD_IO_ACCESS
#else
#define CO_RTT_CONFIG_PDO_OD_IO_ACCESS 0
#endif /* defined(PKG_CANOPENNODE_PDO_OD_IO_ACCESS) */
#if defined(PKG_CANOPENNODE_PDO_BITWISE_MAPPING)
#define CO_RTT_CONFIG_PDO_BITWISE_MAPPING CO_CONFIG_PDO_BITWISE_MAPPING
#else
#define CO_RTT_CONFIG_PDO_BITWISE_MAPPING 0
#endif /* defined(PKG_CANOPENNODE_PDO_BITWISE_MAPPING) */
#define CO_CONFIG_PDO                 (CO_RTT_CONFIG_RPDO \
                                      | CO_RTT_CONFIG_TPDO \
                                      | CO_RTT_CONFIG_RPDO_TIMERS \
                                      | CO_RTT_CONFIG_TPDO_TIMERS \
                                      | CO_RTT_CONFIG_PDO_SYNC \
                                      | CO_RTT_CONFIG_PDO_OD_IO_ACCESS \
                                      | CO_RTT_CONFIG_PDO_BITWISE_MAPPING \
                                      | CO_CONFIG_GLOBAL_RT_FLAG_CALLBACK_PRE \
                                      | CO_CONFIG_GLOBAL_FLAG_TIMERNEXT \
                                      | CO_CONFIG_GLOBAL_FLAG_OD_DYNAMIC)
#else
#define CO_CONFIG_PDO 0
#endif /* defined(PKG_CANOPENNODE_USING_PDO) */

#if defined(PKG_CANOPENNODE_USING_STORAGE)
#define CO_CONFIG_STORAGE CO_CONFIG_STORAGE_ENABLE
#else
#define CO_CONFIG_STORAGE 0
#endif /* defined(PKG_CANOPENNODE_USING_STORAGE) */
#if defined(PKG_CANOPENNODE_STORAGE_MAX_ENTRIES_COUNT)
#define CO_CONFIG_STORAGE_MAX_ENTRIES_COUNT PKG_CANOPENNODE_STORAGE_MAX_ENTRIES_COUNT
#else
#define CO_CONFIG_STORAGE_MAX_ENTRIES_COUNT 1U
#endif /* defined(PKG_CANOPENNODE_STORAGE_MAX_ENTRIES_COUNT) */

#if defined(PKG_CANOPENNODE_USING_LEDS)
#define CO_CONFIG_LEDS (CO_CONFIG_LEDS_ENABLE | CO_CONFIG_GLOBAL_FLAG_TIMERNEXT)
#else
#define CO_CONFIG_LEDS 0
#endif /* defined(PKG_CANOPENNODE_USING_LEDS) */

#if defined(PKG_CANOPENNODE_USING_GFC)
#if defined(PKG_CANOPENNODE_GFC_CONSUMER)
#define CO_RTT_CONFIG_GFC_CONSUMER CO_CONFIG_GFC_CONSUMER
#else
#define CO_RTT_CONFIG_GFC_CONSUMER 0
#endif /* defined(PKG_CANOPENNODE_GFC_CONSUMER) */
#if defined(PKG_CANOPENNODE_GFC_PRODUCER)
#define CO_RTT_CONFIG_GFC_PRODUCER CO_CONFIG_GFC_PRODUCER
#else
#define CO_RTT_CONFIG_GFC_PRODUCER 0
#endif /* defined(PKG_CANOPENNODE_GFC_PRODUCER) */
#define CO_CONFIG_GFC (CO_CONFIG_GFC_ENABLE | CO_RTT_CONFIG_GFC_CONSUMER | CO_RTT_CONFIG_GFC_PRODUCER)
#else
#define CO_CONFIG_GFC 0
#endif /* defined(PKG_CANOPENNODE_USING_GFC) */

#if defined(PKG_CANOPENNODE_USING_SRDO)
#if defined(PKG_CANOPENNODE_SRDO_CHECK_TX)
#define CO_RTT_CONFIG_SRDO_CHECK_TX CO_CONFIG_SRDO_CHECK_TX
#else
#define CO_RTT_CONFIG_SRDO_CHECK_TX 0
#endif /* defined(PKG_CANOPENNODE_SRDO_CHECK_TX) */
#define CO_CONFIG_SRDO                (CO_CONFIG_SRDO_ENABLE \
                                      | CO_RTT_CONFIG_SRDO_CHECK_TX \
                                      | CO_CONFIG_GLOBAL_RT_FLAG_CALLBACK_PRE \
                                      | CO_CONFIG_GLOBAL_FLAG_TIMERNEXT)
#else
#define CO_CONFIG_SRDO 0
#endif /* defined(PKG_CANOPENNODE_USING_SRDO) */
#if defined(PKG_CANOPENNODE_SRDO_MINIMUM_DELAY)
#define CO_CONFIG_SRDO_MINIMUM_DELAY   PKG_CANOPENNODE_SRDO_MINIMUM_DELAY
#else
#define CO_CONFIG_SRDO_MINIMUM_DELAY   0
#endif /* defined(PKG_CANOPENNODE_SRDO_MINIMUM_DELAY) */

#if defined(PKG_CANOPENNODE_USING_LSS_SLAVE)
#define CO_RTT_CONFIG_LSS_SLAVE CO_CONFIG_LSS_SLAVE
#else
#define CO_RTT_CONFIG_LSS_SLAVE 0
#endif /* defined(PKG_CANOPENNODE_USING_LSS_SLAVE) */
#if defined(PKG_CANOPENNODE_LSS_SLAVE_FASTSCAN_DIRECT_RESPOND)
#define CO_RTT_CONFIG_LSS_FASTSCAN CO_CONFIG_LSS_SLAVE_FASTSCAN_DIRECT_RESPOND
#else
#define CO_RTT_CONFIG_LSS_FASTSCAN 0
#endif /* defined(PKG_CANOPENNODE_LSS_SLAVE_FASTSCAN_DIRECT_RESPOND) */
#if defined(PKG_CANOPENNODE_USING_LSS_MASTER)
#define CO_RTT_CONFIG_LSS_MASTER CO_CONFIG_LSS_MASTER
#else
#define CO_RTT_CONFIG_LSS_MASTER 0
#endif /* defined(PKG_CANOPENNODE_USING_LSS_MASTER) */
#define CO_CONFIG_LSS                 (CO_RTT_CONFIG_LSS_SLAVE \
                                      | CO_RTT_CONFIG_LSS_FASTSCAN \
                                      | CO_RTT_CONFIG_LSS_MASTER \
                                      | CO_CONFIG_GLOBAL_FLAG_CALLBACK_PRE)

#if defined(PKG_CANOPENNODE_USING_GATEWAY_ASCII)
#if defined(PKG_CANOPENNODE_GATEWAY_MULTI_NET)
#define CO_RTT_CONFIG_GTW_MULTI_NET CO_CONFIG_GTW_MULTI_NET
#else
#define CO_RTT_CONFIG_GTW_MULTI_NET 0
#endif /* defined(PKG_CANOPENNODE_GATEWAY_MULTI_NET) */
#if defined(PKG_CANOPENNODE_GATEWAY_ASCII_SDO)
#define CO_RTT_CONFIG_GTW_ASCII_SDO CO_CONFIG_GTW_ASCII_SDO
#else
#define CO_RTT_CONFIG_GTW_ASCII_SDO 0
#endif /* defined(PKG_CANOPENNODE_GATEWAY_ASCII_SDO) */
#if defined(PKG_CANOPENNODE_GATEWAY_ASCII_NMT)
#define CO_RTT_CONFIG_GTW_ASCII_NMT CO_CONFIG_GTW_ASCII_NMT
#else
#define CO_RTT_CONFIG_GTW_ASCII_NMT 0
#endif /* defined(PKG_CANOPENNODE_GATEWAY_ASCII_NMT) */
#if defined(PKG_CANOPENNODE_GATEWAY_ASCII_LSS)
#define CO_RTT_CONFIG_GTW_ASCII_LSS CO_CONFIG_GTW_ASCII_LSS
#else
#define CO_RTT_CONFIG_GTW_ASCII_LSS 0
#endif /* defined(PKG_CANOPENNODE_GATEWAY_ASCII_LSS) */
#if defined(PKG_CANOPENNODE_GATEWAY_ASCII_LOG)
#define CO_RTT_CONFIG_GTW_ASCII_LOG CO_CONFIG_GTW_ASCII_LOG
#else
#define CO_RTT_CONFIG_GTW_ASCII_LOG 0
#endif /* defined(PKG_CANOPENNODE_GATEWAY_ASCII_LOG) */
#if defined(PKG_CANOPENNODE_GATEWAY_ASCII_ERROR_DESC)
#define CO_RTT_CONFIG_GTW_ASCII_ERROR_DESC CO_CONFIG_GTW_ASCII_ERROR_DESC
#else
#define CO_RTT_CONFIG_GTW_ASCII_ERROR_DESC 0
#endif /* defined(PKG_CANOPENNODE_GATEWAY_ASCII_ERROR_DESC) */
#if defined(PKG_CANOPENNODE_GATEWAY_ASCII_PRINT_HELP)
#define CO_RTT_CONFIG_GTW_ASCII_PRINT_HELP CO_CONFIG_GTW_ASCII_PRINT_HELP
#else
#define CO_RTT_CONFIG_GTW_ASCII_PRINT_HELP 0
#endif /* defined(PKG_CANOPENNODE_GATEWAY_ASCII_PRINT_HELP) */
#if defined(PKG_CANOPENNODE_GATEWAY_ASCII_PRINT_LEDS)
#define CO_RTT_CONFIG_GTW_ASCII_PRINT_LEDS CO_CONFIG_GTW_ASCII_PRINT_LEDS
#else
#define CO_RTT_CONFIG_GTW_ASCII_PRINT_LEDS 0
#endif /* defined(PKG_CANOPENNODE_GATEWAY_ASCII_PRINT_LEDS) */
#define CO_CONFIG_GTW                 (CO_RTT_CONFIG_GTW_MULTI_NET \
                                      | CO_CONFIG_GTW_ASCII \
                                      | CO_RTT_CONFIG_GTW_ASCII_SDO \
                                      | CO_RTT_CONFIG_GTW_ASCII_NMT \
                                      | CO_RTT_CONFIG_GTW_ASCII_LSS \
                                      | CO_RTT_CONFIG_GTW_ASCII_LOG \
                                      | CO_RTT_CONFIG_GTW_ASCII_ERROR_DESC \
                                      | CO_RTT_CONFIG_GTW_ASCII_PRINT_HELP \
                                      | CO_RTT_CONFIG_GTW_ASCII_PRINT_LEDS)
#else
#define CO_CONFIG_GTW 0
#endif /* defined(PKG_CANOPENNODE_USING_GATEWAY_ASCII) */
#if defined(PKG_CANOPENNODE_GTW_BLOCK_DL_LOOP)
#define CO_CONFIG_GTW_BLOCK_DL_LOOP    PKG_CANOPENNODE_GTW_BLOCK_DL_LOOP
#else
#define CO_CONFIG_GTW_BLOCK_DL_LOOP    1
#endif /* defined(PKG_CANOPENNODE_GTW_BLOCK_DL_LOOP) */
#if defined(PKG_CANOPENNODE_GTWA_COMM_BUF_SIZE)
#define CO_CONFIG_GTWA_COMM_BUF_SIZE   PKG_CANOPENNODE_GTWA_COMM_BUF_SIZE
#else
#define CO_CONFIG_GTWA_COMM_BUF_SIZE   200
#endif /* defined(PKG_CANOPENNODE_GTWA_COMM_BUF_SIZE) */
#if defined(PKG_CANOPENNODE_GTWA_LOG_BUF_SIZE)
#define CO_CONFIG_GTWA_LOG_BUF_SIZE    PKG_CANOPENNODE_GTWA_LOG_BUF_SIZE
#else
#define CO_CONFIG_GTWA_LOG_BUF_SIZE    2000
#endif /* defined(PKG_CANOPENNODE_GTWA_LOG_BUF_SIZE) */

#if defined(PKG_CANOPENNODE_USING_CRC16)
#if defined(PKG_CANOPENNODE_CRC16_EXTERNAL)
#define CO_RTT_CONFIG_CRC16_EXTERNAL CO_CONFIG_CRC16_EXTERNAL
#else
#define CO_RTT_CONFIG_CRC16_EXTERNAL 0
#endif /* defined(PKG_CANOPENNODE_CRC16_EXTERNAL) */
#define CO_CONFIG_CRC16 (CO_CONFIG_CRC16_ENABLE | CO_RTT_CONFIG_CRC16_EXTERNAL)
#else
#define CO_CONFIG_CRC16 0
#endif /* defined(PKG_CANOPENNODE_USING_CRC16) */

#if defined(PKG_CANOPENNODE_USING_FIFO)
#if defined(PKG_CANOPENNODE_FIFO_ALT_READ)
#define CO_RTT_CONFIG_FIFO_ALT_READ CO_CONFIG_FIFO_ALT_READ
#else
#define CO_RTT_CONFIG_FIFO_ALT_READ 0
#endif /* defined(PKG_CANOPENNODE_FIFO_ALT_READ) */
#if defined(PKG_CANOPENNODE_FIFO_CRC16_CCITT)
#define CO_RTT_CONFIG_FIFO_CRC16_CCITT CO_CONFIG_FIFO_CRC16_CCITT
#else
#define CO_RTT_CONFIG_FIFO_CRC16_CCITT 0
#endif /* defined(PKG_CANOPENNODE_FIFO_CRC16_CCITT) */
#if defined(PKG_CANOPENNODE_FIFO_ASCII_COMMANDS)
#define CO_RTT_CONFIG_FIFO_ASCII_COMMANDS CO_CONFIG_FIFO_ASCII_COMMANDS
#else
#define CO_RTT_CONFIG_FIFO_ASCII_COMMANDS 0
#endif /* defined(PKG_CANOPENNODE_FIFO_ASCII_COMMANDS) */
#if defined(PKG_CANOPENNODE_FIFO_ASCII_DATATYPES)
#define CO_RTT_CONFIG_FIFO_ASCII_DATATYPES CO_CONFIG_FIFO_ASCII_DATATYPES
#else
#define CO_RTT_CONFIG_FIFO_ASCII_DATATYPES 0
#endif /* defined(PKG_CANOPENNODE_FIFO_ASCII_DATATYPES) */
#define CO_CONFIG_FIFO                (CO_CONFIG_FIFO_ENABLE \
                                      | CO_RTT_CONFIG_FIFO_ALT_READ \
                                      | CO_RTT_CONFIG_FIFO_CRC16_CCITT \
                                      | CO_RTT_CONFIG_FIFO_ASCII_COMMANDS \
                                      | CO_RTT_CONFIG_FIFO_ASCII_DATATYPES)
#else
#define CO_CONFIG_FIFO 0
#endif /* defined(PKG_CANOPENNODE_USING_FIFO) */

#if defined(PKG_CANOPENNODE_USING_TRACE)
#if defined(PKG_CANOPENNODE_TRACE_OWN_INTTYPES)
#define CO_RTT_CONFIG_TRACE_OWN_INTTYPES CO_CONFIG_TRACE_OWN_INTTYPES
#else
#define CO_RTT_CONFIG_TRACE_OWN_INTTYPES 0
#endif /* defined(PKG_CANOPENNODE_TRACE_OWN_INTTYPES) */
#define CO_CONFIG_TRACE (CO_CONFIG_TRACE_ENABLE | CO_RTT_CONFIG_TRACE_OWN_INTTYPES)
#else
#define CO_CONFIG_TRACE 0
#endif /* defined(PKG_CANOPENNODE_USING_TRACE) */

#if defined(PKG_CANOPENNODE_USING_DEBUG)
#if defined(PKG_CANOPENNODE_DEBUG_COMMON)
#define CO_RTT_CONFIG_DEBUG_COMMON     CO_CONFIG_DEBUG_COMMON
#else
#define CO_RTT_CONFIG_DEBUG_COMMON     0
#endif /* defined(PKG_CANOPENNODE_DEBUG_COMMON) */

#if defined(PKG_CANOPENNODE_DEBUG_SDO_CLIENT)
#define CO_RTT_CONFIG_DEBUG_SDO_CLIENT CO_CONFIG_DEBUG_SDO_CLIENT
#else
#define CO_RTT_CONFIG_DEBUG_SDO_CLIENT 0
#endif /* defined(PKG_CANOPENNODE_DEBUG_SDO_CLIENT) */

#if defined(PKG_CANOPENNODE_DEBUG_SDO_SERVER)
#define CO_RTT_CONFIG_DEBUG_SDO_SERVER CO_CONFIG_DEBUG_SDO_SERVER
#else
#define CO_RTT_CONFIG_DEBUG_SDO_SERVER 0
#endif /* defined(PKG_CANOPENNODE_DEBUG_SDO_SERVER) */

#ifndef CO_CONFIG_DEBUG
#define CO_CONFIG_DEBUG                (CO_RTT_CONFIG_DEBUG_COMMON \
                                      | CO_RTT_CONFIG_DEBUG_SDO_CLIENT \
                                      | CO_RTT_CONFIG_DEBUG_SDO_SERVER)
#endif /* CO_CONFIG_DEBUG */

#if defined(RT_USING_ULOG)
#ifndef LOG_TAG
#define LOG_TAG                        "canopen"
#endif /* LOG_TAG */
#ifndef LOG_LVL
#define LOG_LVL                        LOG_LVL_DBG
#endif /* LOG_LVL */
#include <ulog.h>
#define CO_DEBUG_COMMON(msg)           LOG_D("%s", (msg))
#endif /* defined(RT_USING_ULOG) */
#endif /* defined(PKG_CANOPENNODE_USING_DEBUG) */

/* Exported types ------------------------------------------------------------*/

/* Exported variables ---------------------------------------------------------*/

/* Exported functions prototypes ---------------------------------------------*/

#endif /* CO_CONFIG_RTT_H_ */
