#ifndef PROFILE_MASTER_RTT_HOST_STUB_CO_MAINLINE_RTT_H
#define PROFILE_MASTER_RTT_HOST_STUB_CO_MAINLINE_RTT_H
#include "CO_app_RTT.h"
void CO_RTT_mainlineWakeup(CANopenNodeRTT *app);
#endif /* PROFILE_MASTER_RTT_HOST_STUB_CO_MAINLINE_RTT_H */
