#ifndef PROFILE_MASTER_RTT_HOST_STUB_OD_H
#define PROFILE_MASTER_RTT_HOST_STUB_OD_H
#ifndef OD_CNT_SDO_CLI
#define OD_CNT_SDO_CLI 1U
#endif /* OD_CNT_SDO_CLI */
#endif /* PROFILE_MASTER_RTT_HOST_STUB_OD_H */
