/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
#include "301/CO_ODinterface.h"
#include "OD.h"

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
OD_ATTR_PERSIST_COMM OD_PERSIST_COMM_t OD_PERSIST_COMM = {
    .x1000_deviceType = 0x00000000,
    .x1005_COB_ID_SYNCMessage = 0x00000080,
    .x1006_communicationCyclePeriod = 0x00000000,
    .x1007_synchronousWindowLength = 0x00000000,
    .x1008_manufacturerDeviceName = {'r', 't', 't', ' ', 'd', 'e', 'm', 'o', 0},
    .x1009_manufacturerHardwareVersion = {'V', '1', '.', '0', '.', '0', 0},
    .x100A_manufacturerSoftwareVersion = {'V', '1', '.', '0', '.', '0', '.', 'A', 0},
    .x1012_COB_IDTimeStampObject = 0x00000100,
    .x1014_COB_ID_EMCY = 0x00000080,
    .x1015_inhibitTimeEMCY = 0x0000,
    .x1016_consumerHeartbeatTime_sub0 = 0x08,
    .x1016_consumerHeartbeatTime = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x1017_producerHeartbeatTime = 0x0000,
    .x1018_identity = {
        .highestSub_indexSupported = 0x04,
        .vendor_ID = 0x00000000,
        .productCode = 0x00000001,
        .revisionNumber = 0x00010000,
        .serialNumber = 0x00000001
    },
    .x1019_synchronousCounterOverflowValue = 0x00,
    .x1280_SDOClientParameter = {
        .highestSub_indexSupported = 0x03,
        .COB_IDClientToServerTx = 0x80000000,
        .COB_IDServerToClientRx = 0x80000000,
        .node_IDOfTheSDOServer = 0x01
    },
    .x1300_globalFail_safeCommandParameter = 0x01,
    .x1301_SRDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .informationDirection = 0x02,
        .safetyCycleTime = 0x0064,
        .safetyRelatedValidationTime = 0x14,
        .transmissionType = 0xFE,
        .COB_ID1Normal = 0x00000101,
        .COB_ID2Inverted = 0x00000102
    },
    .x1302_SRDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .informationDirection = 0x01,
        .safetyCycleTime = 0x0064,
        .safetyRelatedValidationTime = 0x14,
        .transmissionType = 0xFE,
        .COB_ID1Normal = 0x00000103,
        .COB_ID2Inverted = 0x00000104
    },
    .x1381_SRDOMappingParameter = {
        .numberOfMappedApplicationObjectsInSRDO = 0x02,
        .applicationObject1 = 0x23060120,
        .applicationObject2 = 0x23060220
    },
    .x1382_SRDOMappingParameter = {
        .numberOfMappedApplicationObjectsInSRDO = 0x02,
        .applicationObject1 = 0x23060320,
        .applicationObject2 = 0x23060420
    },
    .x13FE_SRDOConfigurationValid = 0xA5,
    .x13FF_SRDOChecksum_sub0 = 0x02,
    .x13FF_SRDOChecksum = {0xA1B7, 0x49D8},
    .x1400_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x00000200,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1401_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x80000300,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1402_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x80000400,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1403_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x80000500,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1600_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x01,
        .applicationObject1 = 0x22000020,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1601_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x03,
        .applicationObject1 = 0x60400010,
        .applicationObject2 = 0x60600008,
        .applicationObject3 = 0x607A0020,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1602_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x03,
        .applicationObject1 = 0x68400010,
        .applicationObject2 = 0x68600008,
        .applicationObject3 = 0x687A0020,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1603_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x03,
        .applicationObject1 = 0x70400010,
        .applicationObject2 = 0x70600008,
        .applicationObject3 = 0x707A0020,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1800_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0x40000180,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .eventTimer = 0x03E8,
        .SYNCStartValue = 0x00
    },
    .x1801_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0xC0000280,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1802_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0xC0000380,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1803_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0xC0000480,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1804_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0xC0000000,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1A00_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x02,
        .applicationObject1 = 0x21000020,
        .applicationObject2 = 0x21010020,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1A01_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x03,
        .applicationObject1 = 0x60410010,
        .applicationObject2 = 0x60610008,
        .applicationObject3 = 0x60640020,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1A02_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x03,
        .applicationObject1 = 0x68410010,
        .applicationObject2 = 0x68610008,
        .applicationObject3 = 0x68640020,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1A03_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x03,
        .applicationObject1 = 0x70410010,
        .applicationObject2 = 0x70610008,
        .applicationObject3 = 0x70640020,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1A04_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    }
};

OD_ATTR_RAM OD_RAM_t OD_RAM = {
    .x1001_errorRegister = 0x00,
    .x1002_manufacturerStatusRegister = 0x00000000,
    .x1010_storeParameters_sub0 = 0x04,
    .x1010_storeParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1011_restoreDefaultParameters_sub0 = 0x04,
    .x1011_restoreDefaultParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1013_highResolutionTimeStamp = 0x00000000,
    .x1200_SDOServerParameter = {
        .highestSub_indexSupported = 0x02,
        .COB_IDClientToServerRx = 0x00000600,
        .COB_IDServerToClientTx = 0x00000580
    },
    .x2100_status_value = 0x00000000,
    .x2101_counter_value = 0x00000000,
    .x2200_control_value = 0x00000000,
    .x2300_time_consumer_diagnostic = {
        .highestSub_indexSupported = 0x03,
        .valid_time_rx_count = 0x00000000,
        .applied_time_ms = 0x00000000,
        .applied_time_days = 0x0000
    },
    .x2301_emcy_consumer_diagnostic = {
        .highestSub_indexSupported = 0x07,
        .remote_rx_count = 0x00000000,
        .last_source_node_id = 0x00,
        .last_cob_id = 0x0000,
        .last_error_code = 0x0000,
        .last_error_register = 0x00,
        .last_error_bit = 0x00,
        .last_info_code = 0x00000000
    },
    .x2302_gfc_diagnostic = {
        .highestSub_indexSupported = 0x05,
        .rx_count = 0x00000000,
        .safe_requested = 0x00,
        .producer_request_seq = 0x00000000,
        .producer_complete_seq = 0x00000000,
        .producer_result = 0
    },
    .x2303_sdo_client_test = {
        .highestSub_indexSupported = 0x0F,
        .request_seq = 0x00000000,
        .command = 0x00,
        .remote_node = 0x00,
        .index = 0x0000,
        .sub_index = 0x00,
        .payload_size = 0x00000000,
        .probe_value = 0x00000000,
        .flags = 0x00,
        .active_seq = 0x00000000,
        .complete_seq = 0x00000000,
        .result = 0,
        .abort_code = 0x00000000,
        .transferred_size = 0x00000000,
        .result_value = 0x00000000,
        .checksum = 0x00000000
    },
    .x2305_storage_diagnostic = {
        .highestSub_indexSupported = 0x1A,
        .request_seq = 0x00000000,
        .command = 0x00,
        .entry_sub_index = 0x02,
        .raw_offset = 0x00000000,
        .raw_size = 0x04,
        .raw_value = 0x00000000,
        .active_seq = 0x00000000,
        .complete_seq = 0x00000000,
        .result = 0,
        .startup_state = 0x00,
        .startup_result = 0,
        .startup_error = 0x00000000,
        .storage_offset = 0x00000000,
        .eeprom_size = 0x00000000,
        .page_size = 0x0000,
        .addr_input = 0x00,
        .signature_address = 0x00000000,
        .data_address = 0x00000000,
        .data_length = 0x00000000,
        .raw_start = 0x00000000,
        .raw_length = 0x00000000,
        .signature_value = 0x00000000,
        .backup_valid = 0x00,
        .backup_crc = 0x0000,
        .startup_seq = 0x00000000,
        .startup_probe = 0x0000
    },
    .x2306_srdo_diagnostic = {
        .highestSub_indexSupported = 0x0B,
        .rx_normal = 0x00000000,
        .rx_inverted = 0xFFFFFFFF,
        .tx_normal = 0x12345678,
        .tx_inverted = 0xEDCBA987,
        .aggregate_state = 0,
        .rx_state = 0,
        .tx_state = 0,
        .state_seq = 0x00000000,
        .tx_request_seq = 0x00000000,
        .tx_complete_seq = 0x00000000,
        .tx_request_result = 0
    },
    .x603F_axis0ErrorCode = 0x0000,
    .x6040_axis0Controlword = 0x0000,
    .x6041_axis0Statusword = 0x0040,
    .x6060_axis0ModesOfOperation = 0,
    .x6061_axis0ModesOfOperationDisplay = 0,
    .x6064_axis0PositionActualValue = 0,
    .x606C_axis0VelocityActualValue = 0,
    .x607A_axis0TargetPosition = 0,
    .x607C_axis0HomeOffset = 0,
    .x6081_axis0ProfileVelocity = 0x00000000,
    .x6083_axis0ProfileAcceleration = 0x00000000,
    .x6084_axis0ProfileDeceleration = 0x00000000,
    .x6085_axis0QuickStopDeceleration = 0x00000000,
    .x6086_axis0MotionProfileType = 0,
    .x6098_axis0HomingMethod = 0,
    .x6099_axis0HomingSpeeds = {
        .highestSub_indexSupported = 0x02,
        .speedDuringSearchForSwitch = 0x00000000,
        .speedDuringSearchForZero = 0x00000000
    },
    .x609A_axis0HomingAcceleration = 0x00000000,
    .x60FF_axis0TargetVelocity = 0,
    .x6502_axis0SupportedDriveModes = 0x00000000,
    .x683F_axis1ErrorCode = 0x0000,
    .x6840_axis1Controlword = 0x0000,
    .x6841_axis1Statusword = 0x0040,
    .x6860_axis1ModesOfOperation = 0,
    .x6861_axis1ModesOfOperationDisplay = 0,
    .x6864_axis1PositionActualValue = 0,
    .x686C_axis1VelocityActualValue = 0,
    .x687A_axis1TargetPosition = 0,
    .x687C_axis1HomeOffset = 0,
    .x6881_axis1ProfileVelocity = 0x00000000,
    .x6883_axis1ProfileAcceleration = 0x00000000,
    .x6884_axis1ProfileDeceleration = 0x00000000,
    .x6885_axis1QuickStopDeceleration = 0x00000000,
    .x6886_axis1MotionProfileType = 0,
    .x6898_axis1HomingMethod = 0,
    .x6899_axis1HomingSpeeds = {
        .highestSub_indexSupported = 0x02,
        .speedDuringSearchForSwitch = 0x00000000,
        .speedDuringSearchForZero = 0x00000000
    },
    .x689A_axis1HomingAcceleration = 0x00000000,
    .x68FF_axis1TargetVelocity = 0,
    .x6D02_axis1SupportedDriveModes = 0x00000000,
    .x703F_axis2ErrorCode = 0x0000,
    .x7040_axis2Controlword = 0x0000,
    .x7041_axis2Statusword = 0x0040,
    .x7060_axis2ModesOfOperation = 0,
    .x7061_axis2ModesOfOperationDisplay = 0,
    .x7064_axis2PositionActualValue = 0,
    .x706C_axis2VelocityActualValue = 0,
    .x707A_axis2TargetPosition = 0,
    .x707C_axis2HomeOffset = 0,
    .x7081_axis2ProfileVelocity = 0x00000000,
    .x7083_axis2ProfileAcceleration = 0x00000000,
    .x7084_axis2ProfileDeceleration = 0x00000000,
    .x7085_axis2QuickStopDeceleration = 0x00000000,
    .x7086_axis2MotionProfileType = 0,
    .x7098_axis2HomingMethod = 0,
    .x7099_axis2HomingSpeeds = {
        .highestSub_indexSupported = 0x02,
        .speedDuringSearchForSwitch = 0x00000000,
        .speedDuringSearchForZero = 0x00000000
    },
    .x709A_axis2HomingAcceleration = 0x00000000,
    .x70FF_axis2TargetVelocity = 0,
    .x7502_axis2SupportedDriveModes = 0x00000000
};



/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_var_t o_1002_manufacturerStatusRegister;
    OD_obj_array_t o_1003_pre_definedErrorField;
    OD_obj_var_t o_1005_COB_ID_SYNCMessage;
    OD_obj_var_t o_1006_communicationCyclePeriod;
    OD_obj_var_t o_1007_synchronousWindowLength;
    OD_obj_var_t o_1008_manufacturerDeviceName;
    OD_obj_var_t o_1009_manufacturerHardwareVersion;
    OD_obj_var_t o_100A_manufacturerSoftwareVersion;
    OD_obj_array_t o_1010_storeParameters;
    OD_obj_array_t o_1011_restoreDefaultParameters;
    OD_obj_var_t o_1012_COB_IDTimeStampObject;
    OD_obj_var_t o_1013_highResolutionTimeStamp;
    OD_obj_var_t o_1014_COB_ID_EMCY;
    OD_obj_var_t o_1015_inhibitTimeEMCY;
    OD_obj_array_t o_1016_consumerHeartbeatTime;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identity[5];
    OD_obj_var_t o_1019_synchronousCounterOverflowValue;
    OD_obj_record_t o_1200_SDOServerParameter[3];
    OD_obj_record_t o_1280_SDOClientParameter[4];
    OD_obj_var_t o_1300_globalFail_safeCommandParameter;
    OD_obj_record_t o_1301_SRDOCommunicationParameter[7];
    OD_obj_record_t o_1302_SRDOCommunicationParameter[7];
    OD_obj_record_t o_1381_SRDOMappingParameter[3];
    OD_obj_record_t o_1382_SRDOMappingParameter[3];
    OD_obj_var_t o_13FE_SRDOConfigurationValid;
    OD_obj_array_t o_13FF_SRDOChecksum;
    OD_obj_record_t o_1400_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1401_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1402_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1403_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1600_RPDOMappingParameter[9];
    OD_obj_record_t o_1601_RPDOMappingParameter[9];
    OD_obj_record_t o_1602_RPDOMappingParameter[9];
    OD_obj_record_t o_1603_RPDOMappingParameter[9];
    OD_obj_record_t o_1800_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1801_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1802_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1803_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1804_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1A00_TPDOMappingParameter[9];
    OD_obj_record_t o_1A01_TPDOMappingParameter[9];
    OD_obj_record_t o_1A02_TPDOMappingParameter[9];
    OD_obj_record_t o_1A03_TPDOMappingParameter[9];
    OD_obj_record_t o_1A04_TPDOMappingParameter[9];
    OD_obj_var_t o_2100_status_value;
    OD_obj_var_t o_2101_counter_value;
    OD_obj_var_t o_2200_control_value;
    OD_obj_record_t o_2300_time_consumer_diagnostic[4];
    OD_obj_record_t o_2301_emcy_consumer_diagnostic[8];
    OD_obj_record_t o_2302_gfc_diagnostic[6];
    OD_obj_record_t o_2303_sdo_client_test[16];
    OD_obj_var_t o_2304_sdo_server_block_test;
    OD_obj_record_t o_2305_storage_diagnostic[27];
    OD_obj_record_t o_2306_srdo_diagnostic[12];
    OD_obj_var_t o_603F_axis0ErrorCode;
    OD_obj_var_t o_6040_axis0Controlword;
    OD_obj_var_t o_6041_axis0Statusword;
    OD_obj_var_t o_6060_axis0ModesOfOperation;
    OD_obj_var_t o_6061_axis0ModesOfOperationDisplay;
    OD_obj_var_t o_6064_axis0PositionActualValue;
    OD_obj_var_t o_606C_axis0VelocityActualValue;
    OD_obj_var_t o_607A_axis0TargetPosition;
    OD_obj_var_t o_607C_axis0HomeOffset;
    OD_obj_var_t o_6081_axis0ProfileVelocity;
    OD_obj_var_t o_6083_axis0ProfileAcceleration;
    OD_obj_var_t o_6084_axis0ProfileDeceleration;
    OD_obj_var_t o_6085_axis0QuickStopDeceleration;
    OD_obj_var_t o_6086_axis0MotionProfileType;
    OD_obj_var_t o_6098_axis0HomingMethod;
    OD_obj_record_t o_6099_axis0HomingSpeeds[3];
    OD_obj_var_t o_609A_axis0HomingAcceleration;
    OD_obj_var_t o_60FF_axis0TargetVelocity;
    OD_obj_var_t o_6502_axis0SupportedDriveModes;
    OD_obj_var_t o_683F_axis1ErrorCode;
    OD_obj_var_t o_6840_axis1Controlword;
    OD_obj_var_t o_6841_axis1Statusword;
    OD_obj_var_t o_6860_axis1ModesOfOperation;
    OD_obj_var_t o_6861_axis1ModesOfOperationDisplay;
    OD_obj_var_t o_6864_axis1PositionActualValue;
    OD_obj_var_t o_686C_axis1VelocityActualValue;
    OD_obj_var_t o_687A_axis1TargetPosition;
    OD_obj_var_t o_687C_axis1HomeOffset;
    OD_obj_var_t o_6881_axis1ProfileVelocity;
    OD_obj_var_t o_6883_axis1ProfileAcceleration;
    OD_obj_var_t o_6884_axis1ProfileDeceleration;
    OD_obj_var_t o_6885_axis1QuickStopDeceleration;
    OD_obj_var_t o_6886_axis1MotionProfileType;
    OD_obj_var_t o_6898_axis1HomingMethod;
    OD_obj_record_t o_6899_axis1HomingSpeeds[3];
    OD_obj_var_t o_689A_axis1HomingAcceleration;
    OD_obj_var_t o_68FF_axis1TargetVelocity;
    OD_obj_var_t o_6D02_axis1SupportedDriveModes;
    OD_obj_var_t o_703F_axis2ErrorCode;
    OD_obj_var_t o_7040_axis2Controlword;
    OD_obj_var_t o_7041_axis2Statusword;
    OD_obj_var_t o_7060_axis2ModesOfOperation;
    OD_obj_var_t o_7061_axis2ModesOfOperationDisplay;
    OD_obj_var_t o_7064_axis2PositionActualValue;
    OD_obj_var_t o_706C_axis2VelocityActualValue;
    OD_obj_var_t o_707A_axis2TargetPosition;
    OD_obj_var_t o_707C_axis2HomeOffset;
    OD_obj_var_t o_7081_axis2ProfileVelocity;
    OD_obj_var_t o_7083_axis2ProfileAcceleration;
    OD_obj_var_t o_7084_axis2ProfileDeceleration;
    OD_obj_var_t o_7085_axis2QuickStopDeceleration;
    OD_obj_var_t o_7086_axis2MotionProfileType;
    OD_obj_var_t o_7098_axis2HomingMethod;
    OD_obj_record_t o_7099_axis2HomingSpeeds[3];
    OD_obj_var_t o_709A_axis2HomingAcceleration;
    OD_obj_var_t o_70FF_axis2TargetVelocity;
    OD_obj_var_t o_7502_axis2SupportedDriveModes;
} ODObjs_t;

static CO_PROGMEM ODObjs_t ODObjs = {
    .o_1000_deviceType = {
        .dataOrig = &OD_PERSIST_COMM.x1000_deviceType,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_1001_errorRegister = {
        .dataOrig = &OD_RAM.x1001_errorRegister,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_1002_manufacturerStatusRegister = {
        .dataOrig = &OD_RAM.x1002_manufacturerStatusRegister,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_1003_pre_definedErrorField = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_RW,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1005_COB_ID_SYNCMessage = {
        .dataOrig = &OD_PERSIST_COMM.x1005_COB_ID_SYNCMessage,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1006_communicationCyclePeriod = {
        .dataOrig = &OD_PERSIST_COMM.x1006_communicationCyclePeriod,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1007_synchronousWindowLength = {
        .dataOrig = &OD_PERSIST_COMM.x1007_synchronousWindowLength,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1008_manufacturerDeviceName = {
        .dataOrig = &OD_PERSIST_COMM.x1008_manufacturerDeviceName[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 8
    },
    .o_1009_manufacturerHardwareVersion = {
        .dataOrig = &OD_PERSIST_COMM.x1009_manufacturerHardwareVersion[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 6
    },
    .o_100A_manufacturerSoftwareVersion = {
        .dataOrig = &OD_PERSIST_COMM.x100A_manufacturerSoftwareVersion[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 8
    },
    .o_1010_storeParameters = {
        .dataOrig0 = &OD_RAM.x1010_storeParameters_sub0,
        .dataOrig = &OD_RAM.x1010_storeParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1011_restoreDefaultParameters = {
        .dataOrig0 = &OD_RAM.x1011_restoreDefaultParameters_sub0,
        .dataOrig = &OD_RAM.x1011_restoreDefaultParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1012_COB_IDTimeStampObject = {
        .dataOrig = &OD_PERSIST_COMM.x1012_COB_IDTimeStampObject,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1013_highResolutionTimeStamp = {
        .dataOrig = &OD_RAM.x1013_highResolutionTimeStamp,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_1014_COB_ID_EMCY = {
        .dataOrig = &OD_PERSIST_COMM.x1014_COB_ID_EMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1015_inhibitTimeEMCY = {
        .dataOrig = &OD_PERSIST_COMM.x1015_inhibitTimeEMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1016_consumerHeartbeatTime = {
        .dataOrig0 = &OD_PERSIST_COMM.x1016_consumerHeartbeatTime_sub0,
        .dataOrig = &OD_PERSIST_COMM.x1016_consumerHeartbeatTime[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1017_producerHeartbeatTime = {
        .dataOrig = &OD_PERSIST_COMM.x1017_producerHeartbeatTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1018_identity = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.vendor_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.productCode,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.revisionNumber,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.serialNumber,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1019_synchronousCounterOverflowValue = {
        .dataOrig = &OD_PERSIST_COMM.x1019_synchronousCounterOverflowValue,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_1200_SDOServerParameter = {
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.COB_IDClientToServerRx,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.COB_IDServerToClientTx,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1280_SDOClientParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.COB_IDClientToServerTx,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.COB_IDServerToClientRx,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.node_IDOfTheSDOServer,
            .subIndex = 3,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1300_globalFail_safeCommandParameter = {
        .dataOrig = &OD_PERSIST_COMM.x1300_globalFail_safeCommandParameter,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_1301_SRDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1301_SRDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1301_SRDOCommunicationParameter.informationDirection,
            .subIndex = 1,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1301_SRDOCommunicationParameter.safetyCycleTime,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1301_SRDOCommunicationParameter.safetyRelatedValidationTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1301_SRDOCommunicationParameter.transmissionType,
            .subIndex = 4,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1301_SRDOCommunicationParameter.COB_ID1Normal,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1301_SRDOCommunicationParameter.COB_ID2Inverted,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1302_SRDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1302_SRDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1302_SRDOCommunicationParameter.informationDirection,
            .subIndex = 1,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1302_SRDOCommunicationParameter.safetyCycleTime,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1302_SRDOCommunicationParameter.safetyRelatedValidationTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1302_SRDOCommunicationParameter.transmissionType,
            .subIndex = 4,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1302_SRDOCommunicationParameter.COB_ID1Normal,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1302_SRDOCommunicationParameter.COB_ID2Inverted,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1381_SRDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1381_SRDOMappingParameter.numberOfMappedApplicationObjectsInSRDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1381_SRDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1381_SRDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1382_SRDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1382_SRDOMappingParameter.numberOfMappedApplicationObjectsInSRDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1382_SRDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1382_SRDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_13FE_SRDOConfigurationValid = {
        .dataOrig = &OD_PERSIST_COMM.x13FE_SRDOConfigurationValid,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_13FF_SRDOChecksum = {
        .dataOrig0 = &OD_PERSIST_COMM.x13FF_SRDOChecksum_sub0,
        .dataOrig = &OD_PERSIST_COMM.x13FF_SRDOChecksum[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_1400_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1401_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1402_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1403_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1600_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1601_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1602_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1603_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1800_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1801_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1802_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1803_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1804_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1804_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1804_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1804_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1804_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1804_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1804_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1A00_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A01_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A02_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A03_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A04_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A04_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A04_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A04_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A04_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A04_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A04_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A04_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A04_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A04_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_2100_status_value = {
        .dataOrig = &OD_RAM.x2100_status_value,
        .attribute = ODA_SDO_RW | ODA_TPDO | ODA_MB,
        .dataLength = 4
    },
    .o_2101_counter_value = {
        .dataOrig = &OD_RAM.x2101_counter_value,
        .attribute = ODA_SDO_RW | ODA_TPDO | ODA_MB,
        .dataLength = 4
    },
    .o_2200_control_value = {
        .dataOrig = &OD_RAM.x2200_control_value,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_2300_time_consumer_diagnostic = {
        {
            .dataOrig = &OD_RAM.x2300_time_consumer_diagnostic.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2300_time_consumer_diagnostic.valid_time_rx_count,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2300_time_consumer_diagnostic.applied_time_ms,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2300_time_consumer_diagnostic.applied_time_days,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 2
        }
    },
    .o_2301_emcy_consumer_diagnostic = {
        {
            .dataOrig = &OD_RAM.x2301_emcy_consumer_diagnostic.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2301_emcy_consumer_diagnostic.remote_rx_count,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2301_emcy_consumer_diagnostic.last_source_node_id,
            .subIndex = 2,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2301_emcy_consumer_diagnostic.last_cob_id,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x2301_emcy_consumer_diagnostic.last_error_code,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x2301_emcy_consumer_diagnostic.last_error_register,
            .subIndex = 5,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2301_emcy_consumer_diagnostic.last_error_bit,
            .subIndex = 6,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2301_emcy_consumer_diagnostic.last_info_code,
            .subIndex = 7,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_2302_gfc_diagnostic = {
        {
            .dataOrig = &OD_RAM.x2302_gfc_diagnostic.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2302_gfc_diagnostic.rx_count,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2302_gfc_diagnostic.safe_requested,
            .subIndex = 2,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2302_gfc_diagnostic.producer_request_seq,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2302_gfc_diagnostic.producer_complete_seq,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2302_gfc_diagnostic.producer_result,
            .subIndex = 5,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_2303_sdo_client_test = {
        {
            .dataOrig = &OD_RAM.x2303_sdo_client_test.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2303_sdo_client_test.request_seq,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2303_sdo_client_test.command,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2303_sdo_client_test.remote_node,
            .subIndex = 3,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2303_sdo_client_test.index,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x2303_sdo_client_test.sub_index,
            .subIndex = 5,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2303_sdo_client_test.payload_size,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2303_sdo_client_test.probe_value,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2303_sdo_client_test.flags,
            .subIndex = 8,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2303_sdo_client_test.active_seq,
            .subIndex = 9,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2303_sdo_client_test.complete_seq,
            .subIndex = 10,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2303_sdo_client_test.result,
            .subIndex = 11,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2303_sdo_client_test.abort_code,
            .subIndex = 12,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2303_sdo_client_test.transferred_size,
            .subIndex = 13,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2303_sdo_client_test.result_value,
            .subIndex = 14,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2303_sdo_client_test.checksum,
            .subIndex = 15,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_2304_sdo_server_block_test = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW,
        .dataLength = 0
    },
    .o_2305_storage_diagnostic = {
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.request_seq,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.command,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.entry_sub_index,
            .subIndex = 3,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.raw_offset,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.raw_size,
            .subIndex = 5,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.raw_value,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.active_seq,
            .subIndex = 7,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.complete_seq,
            .subIndex = 8,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.result,
            .subIndex = 9,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.startup_state,
            .subIndex = 10,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.startup_result,
            .subIndex = 11,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.startup_error,
            .subIndex = 12,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.storage_offset,
            .subIndex = 13,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.eeprom_size,
            .subIndex = 14,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.page_size,
            .subIndex = 15,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.addr_input,
            .subIndex = 16,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.signature_address,
            .subIndex = 17,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.data_address,
            .subIndex = 18,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.data_length,
            .subIndex = 19,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.raw_start,
            .subIndex = 20,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.raw_length,
            .subIndex = 21,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.signature_value,
            .subIndex = 22,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.backup_valid,
            .subIndex = 23,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.backup_crc,
            .subIndex = 24,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.startup_seq,
            .subIndex = 25,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2305_storage_diagnostic.startup_probe,
            .subIndex = 26,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 2
        }
    },
    .o_2306_srdo_diagnostic = {
        {
            .dataOrig = &OD_RAM.x2306_srdo_diagnostic.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2306_srdo_diagnostic.rx_normal,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_RSRDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2306_srdo_diagnostic.rx_inverted,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_RSRDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2306_srdo_diagnostic.tx_normal,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_TSRDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2306_srdo_diagnostic.tx_inverted,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_TSRDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2306_srdo_diagnostic.aggregate_state,
            .subIndex = 5,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2306_srdo_diagnostic.rx_state,
            .subIndex = 6,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2306_srdo_diagnostic.tx_state,
            .subIndex = 7,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2306_srdo_diagnostic.state_seq,
            .subIndex = 8,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2306_srdo_diagnostic.tx_request_seq,
            .subIndex = 9,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2306_srdo_diagnostic.tx_complete_seq,
            .subIndex = 10,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2306_srdo_diagnostic.tx_request_result,
            .subIndex = 11,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_603F_axis0ErrorCode = {
        .dataOrig = &OD_RAM.x603F_axis0ErrorCode,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 2
    },
    .o_6040_axis0Controlword = {
        .dataOrig = &OD_RAM.x6040_axis0Controlword,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6041_axis0Statusword = {
        .dataOrig = &OD_RAM.x6041_axis0Statusword,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6060_axis0ModesOfOperation = {
        .dataOrig = &OD_RAM.x6060_axis0ModesOfOperation,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6061_axis0ModesOfOperationDisplay = {
        .dataOrig = &OD_RAM.x6061_axis0ModesOfOperationDisplay,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_6064_axis0PositionActualValue = {
        .dataOrig = &OD_RAM.x6064_axis0PositionActualValue,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 4
    },
    .o_606C_axis0VelocityActualValue = {
        .dataOrig = &OD_RAM.x606C_axis0VelocityActualValue,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 4
    },
    .o_607A_axis0TargetPosition = {
        .dataOrig = &OD_RAM.x607A_axis0TargetPosition,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_607C_axis0HomeOffset = {
        .dataOrig = &OD_RAM.x607C_axis0HomeOffset,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6081_axis0ProfileVelocity = {
        .dataOrig = &OD_RAM.x6081_axis0ProfileVelocity,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6083_axis0ProfileAcceleration = {
        .dataOrig = &OD_RAM.x6083_axis0ProfileAcceleration,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6084_axis0ProfileDeceleration = {
        .dataOrig = &OD_RAM.x6084_axis0ProfileDeceleration,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6085_axis0QuickStopDeceleration = {
        .dataOrig = &OD_RAM.x6085_axis0QuickStopDeceleration,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6086_axis0MotionProfileType = {
        .dataOrig = &OD_RAM.x6086_axis0MotionProfileType,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_6098_axis0HomingMethod = {
        .dataOrig = &OD_RAM.x6098_axis0HomingMethod,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_6099_axis0HomingSpeeds = {
        {
            .dataOrig = &OD_RAM.x6099_axis0HomingSpeeds.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x6099_axis0HomingSpeeds.speedDuringSearchForSwitch,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x6099_axis0HomingSpeeds.speedDuringSearchForZero,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_609A_axis0HomingAcceleration = {
        .dataOrig = &OD_RAM.x609A_axis0HomingAcceleration,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_60FF_axis0TargetVelocity = {
        .dataOrig = &OD_RAM.x60FF_axis0TargetVelocity,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6502_axis0SupportedDriveModes = {
        .dataOrig = &OD_RAM.x6502_axis0SupportedDriveModes,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_683F_axis1ErrorCode = {
        .dataOrig = &OD_RAM.x683F_axis1ErrorCode,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 2
    },
    .o_6840_axis1Controlword = {
        .dataOrig = &OD_RAM.x6840_axis1Controlword,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6841_axis1Statusword = {
        .dataOrig = &OD_RAM.x6841_axis1Statusword,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6860_axis1ModesOfOperation = {
        .dataOrig = &OD_RAM.x6860_axis1ModesOfOperation,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6861_axis1ModesOfOperationDisplay = {
        .dataOrig = &OD_RAM.x6861_axis1ModesOfOperationDisplay,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_6864_axis1PositionActualValue = {
        .dataOrig = &OD_RAM.x6864_axis1PositionActualValue,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 4
    },
    .o_686C_axis1VelocityActualValue = {
        .dataOrig = &OD_RAM.x686C_axis1VelocityActualValue,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 4
    },
    .o_687A_axis1TargetPosition = {
        .dataOrig = &OD_RAM.x687A_axis1TargetPosition,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_687C_axis1HomeOffset = {
        .dataOrig = &OD_RAM.x687C_axis1HomeOffset,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6881_axis1ProfileVelocity = {
        .dataOrig = &OD_RAM.x6881_axis1ProfileVelocity,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6883_axis1ProfileAcceleration = {
        .dataOrig = &OD_RAM.x6883_axis1ProfileAcceleration,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6884_axis1ProfileDeceleration = {
        .dataOrig = &OD_RAM.x6884_axis1ProfileDeceleration,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6885_axis1QuickStopDeceleration = {
        .dataOrig = &OD_RAM.x6885_axis1QuickStopDeceleration,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6886_axis1MotionProfileType = {
        .dataOrig = &OD_RAM.x6886_axis1MotionProfileType,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_6898_axis1HomingMethod = {
        .dataOrig = &OD_RAM.x6898_axis1HomingMethod,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_6899_axis1HomingSpeeds = {
        {
            .dataOrig = &OD_RAM.x6899_axis1HomingSpeeds.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x6899_axis1HomingSpeeds.speedDuringSearchForSwitch,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x6899_axis1HomingSpeeds.speedDuringSearchForZero,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_689A_axis1HomingAcceleration = {
        .dataOrig = &OD_RAM.x689A_axis1HomingAcceleration,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_68FF_axis1TargetVelocity = {
        .dataOrig = &OD_RAM.x68FF_axis1TargetVelocity,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6D02_axis1SupportedDriveModes = {
        .dataOrig = &OD_RAM.x6D02_axis1SupportedDriveModes,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_703F_axis2ErrorCode = {
        .dataOrig = &OD_RAM.x703F_axis2ErrorCode,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 2
    },
    .o_7040_axis2Controlword = {
        .dataOrig = &OD_RAM.x7040_axis2Controlword,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_7041_axis2Statusword = {
        .dataOrig = &OD_RAM.x7041_axis2Statusword,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_7060_axis2ModesOfOperation = {
        .dataOrig = &OD_RAM.x7060_axis2ModesOfOperation,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_7061_axis2ModesOfOperationDisplay = {
        .dataOrig = &OD_RAM.x7061_axis2ModesOfOperationDisplay,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_7064_axis2PositionActualValue = {
        .dataOrig = &OD_RAM.x7064_axis2PositionActualValue,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 4
    },
    .o_706C_axis2VelocityActualValue = {
        .dataOrig = &OD_RAM.x706C_axis2VelocityActualValue,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 4
    },
    .o_707A_axis2TargetPosition = {
        .dataOrig = &OD_RAM.x707A_axis2TargetPosition,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_707C_axis2HomeOffset = {
        .dataOrig = &OD_RAM.x707C_axis2HomeOffset,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_7081_axis2ProfileVelocity = {
        .dataOrig = &OD_RAM.x7081_axis2ProfileVelocity,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_7083_axis2ProfileAcceleration = {
        .dataOrig = &OD_RAM.x7083_axis2ProfileAcceleration,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_7084_axis2ProfileDeceleration = {
        .dataOrig = &OD_RAM.x7084_axis2ProfileDeceleration,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_7085_axis2QuickStopDeceleration = {
        .dataOrig = &OD_RAM.x7085_axis2QuickStopDeceleration,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_7086_axis2MotionProfileType = {
        .dataOrig = &OD_RAM.x7086_axis2MotionProfileType,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_7098_axis2HomingMethod = {
        .dataOrig = &OD_RAM.x7098_axis2HomingMethod,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_7099_axis2HomingSpeeds = {
        {
            .dataOrig = &OD_RAM.x7099_axis2HomingSpeeds.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x7099_axis2HomingSpeeds.speedDuringSearchForSwitch,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x7099_axis2HomingSpeeds.speedDuringSearchForZero,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_709A_axis2HomingAcceleration = {
        .dataOrig = &OD_RAM.x709A_axis2HomingAcceleration,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_70FF_axis2TargetVelocity = {
        .dataOrig = &OD_RAM.x70FF_axis2TargetVelocity,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_7502_axis2SupportedDriveModes = {
        .dataOrig = &OD_RAM.x7502_axis2SupportedDriveModes,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    }
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static OD_ATTR_OD OD_entry_t ODList[] = {
    {0x1000, 0x01, ODT_VAR, &ODObjs.o_1000_deviceType, NULL},
    {0x1001, 0x01, ODT_VAR, &ODObjs.o_1001_errorRegister, NULL},
    {0x1002, 0x01, ODT_VAR, &ODObjs.o_1002_manufacturerStatusRegister, NULL},
    {0x1003, 0x11, ODT_ARR, &ODObjs.o_1003_pre_definedErrorField, NULL},
    {0x1005, 0x01, ODT_VAR, &ODObjs.o_1005_COB_ID_SYNCMessage, NULL},
    {0x1006, 0x01, ODT_VAR, &ODObjs.o_1006_communicationCyclePeriod, NULL},
    {0x1007, 0x01, ODT_VAR, &ODObjs.o_1007_synchronousWindowLength, NULL},
    {0x1008, 0x01, ODT_VAR, &ODObjs.o_1008_manufacturerDeviceName, NULL},
    {0x1009, 0x01, ODT_VAR, &ODObjs.o_1009_manufacturerHardwareVersion, NULL},
    {0x100A, 0x01, ODT_VAR, &ODObjs.o_100A_manufacturerSoftwareVersion, NULL},
    {0x1010, 0x05, ODT_ARR, &ODObjs.o_1010_storeParameters, NULL},
    {0x1011, 0x05, ODT_ARR, &ODObjs.o_1011_restoreDefaultParameters, NULL},
    {0x1012, 0x01, ODT_VAR, &ODObjs.o_1012_COB_IDTimeStampObject, NULL},
    {0x1013, 0x01, ODT_VAR, &ODObjs.o_1013_highResolutionTimeStamp, NULL},
    {0x1014, 0x01, ODT_VAR, &ODObjs.o_1014_COB_ID_EMCY, NULL},
    {0x1015, 0x01, ODT_VAR, &ODObjs.o_1015_inhibitTimeEMCY, NULL},
    {0x1016, 0x09, ODT_ARR, &ODObjs.o_1016_consumerHeartbeatTime, NULL},
    {0x1017, 0x01, ODT_VAR, &ODObjs.o_1017_producerHeartbeatTime, NULL},
    {0x1018, 0x05, ODT_REC, &ODObjs.o_1018_identity, NULL},
    {0x1019, 0x01, ODT_VAR, &ODObjs.o_1019_synchronousCounterOverflowValue, NULL},
    {0x1200, 0x03, ODT_REC, &ODObjs.o_1200_SDOServerParameter, NULL},
    {0x1280, 0x04, ODT_REC, &ODObjs.o_1280_SDOClientParameter, NULL},
    {0x1300, 0x01, ODT_VAR, &ODObjs.o_1300_globalFail_safeCommandParameter, NULL},
    {0x1301, 0x07, ODT_REC, &ODObjs.o_1301_SRDOCommunicationParameter, NULL},
    {0x1302, 0x07, ODT_REC, &ODObjs.o_1302_SRDOCommunicationParameter, NULL},
    {0x1381, 0x03, ODT_REC, &ODObjs.o_1381_SRDOMappingParameter, NULL},
    {0x1382, 0x03, ODT_REC, &ODObjs.o_1382_SRDOMappingParameter, NULL},
    {0x13FE, 0x01, ODT_VAR, &ODObjs.o_13FE_SRDOConfigurationValid, NULL},
    {0x13FF, 0x03, ODT_ARR, &ODObjs.o_13FF_SRDOChecksum, NULL},
    {0x1400, 0x04, ODT_REC, &ODObjs.o_1400_RPDOCommunicationParameter, NULL},
    {0x1401, 0x04, ODT_REC, &ODObjs.o_1401_RPDOCommunicationParameter, NULL},
    {0x1402, 0x04, ODT_REC, &ODObjs.o_1402_RPDOCommunicationParameter, NULL},
    {0x1403, 0x04, ODT_REC, &ODObjs.o_1403_RPDOCommunicationParameter, NULL},
    {0x1600, 0x09, ODT_REC, &ODObjs.o_1600_RPDOMappingParameter, NULL},
    {0x1601, 0x09, ODT_REC, &ODObjs.o_1601_RPDOMappingParameter, NULL},
    {0x1602, 0x09, ODT_REC, &ODObjs.o_1602_RPDOMappingParameter, NULL},
    {0x1603, 0x09, ODT_REC, &ODObjs.o_1603_RPDOMappingParameter, NULL},
    {0x1800, 0x06, ODT_REC, &ODObjs.o_1800_TPDOCommunicationParameter, NULL},
    {0x1801, 0x06, ODT_REC, &ODObjs.o_1801_TPDOCommunicationParameter, NULL},
    {0x1802, 0x06, ODT_REC, &ODObjs.o_1802_TPDOCommunicationParameter, NULL},
    {0x1803, 0x06, ODT_REC, &ODObjs.o_1803_TPDOCommunicationParameter, NULL},
    {0x1804, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter, NULL},
    {0x1A00, 0x09, ODT_REC, &ODObjs.o_1A00_TPDOMappingParameter, NULL},
    {0x1A01, 0x09, ODT_REC, &ODObjs.o_1A01_TPDOMappingParameter, NULL},
    {0x1A02, 0x09, ODT_REC, &ODObjs.o_1A02_TPDOMappingParameter, NULL},
    {0x1A03, 0x09, ODT_REC, &ODObjs.o_1A03_TPDOMappingParameter, NULL},
    {0x1A04, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter, NULL},
    {0x2100, 0x01, ODT_VAR, &ODObjs.o_2100_status_value, NULL},
    {0x2101, 0x01, ODT_VAR, &ODObjs.o_2101_counter_value, NULL},
    {0x2200, 0x01, ODT_VAR, &ODObjs.o_2200_control_value, NULL},
    {0x2300, 0x04, ODT_REC, &ODObjs.o_2300_time_consumer_diagnostic, NULL},
    {0x2301, 0x08, ODT_REC, &ODObjs.o_2301_emcy_consumer_diagnostic, NULL},
    {0x2302, 0x06, ODT_REC, &ODObjs.o_2302_gfc_diagnostic, NULL},
    {0x2303, 0x10, ODT_REC, &ODObjs.o_2303_sdo_client_test, NULL},
    {0x2304, 0x01, ODT_VAR, &ODObjs.o_2304_sdo_server_block_test, NULL},
    {0x2305, 0x1B, ODT_REC, &ODObjs.o_2305_storage_diagnostic, NULL},
    {0x2306, 0x0C, ODT_REC, &ODObjs.o_2306_srdo_diagnostic, NULL},
    {0x603F, 0x01, ODT_VAR, &ODObjs.o_603F_axis0ErrorCode, NULL},
    {0x6040, 0x01, ODT_VAR, &ODObjs.o_6040_axis0Controlword, NULL},
    {0x6041, 0x01, ODT_VAR, &ODObjs.o_6041_axis0Statusword, NULL},
    {0x6060, 0x01, ODT_VAR, &ODObjs.o_6060_axis0ModesOfOperation, NULL},
    {0x6061, 0x01, ODT_VAR, &ODObjs.o_6061_axis0ModesOfOperationDisplay, NULL},
    {0x6064, 0x01, ODT_VAR, &ODObjs.o_6064_axis0PositionActualValue, NULL},
    {0x606C, 0x01, ODT_VAR, &ODObjs.o_606C_axis0VelocityActualValue, NULL},
    {0x607A, 0x01, ODT_VAR, &ODObjs.o_607A_axis0TargetPosition, NULL},
    {0x607C, 0x01, ODT_VAR, &ODObjs.o_607C_axis0HomeOffset, NULL},
    {0x6081, 0x01, ODT_VAR, &ODObjs.o_6081_axis0ProfileVelocity, NULL},
    {0x6083, 0x01, ODT_VAR, &ODObjs.o_6083_axis0ProfileAcceleration, NULL},
    {0x6084, 0x01, ODT_VAR, &ODObjs.o_6084_axis0ProfileDeceleration, NULL},
    {0x6085, 0x01, ODT_VAR, &ODObjs.o_6085_axis0QuickStopDeceleration, NULL},
    {0x6086, 0x01, ODT_VAR, &ODObjs.o_6086_axis0MotionProfileType, NULL},
    {0x6098, 0x01, ODT_VAR, &ODObjs.o_6098_axis0HomingMethod, NULL},
    {0x6099, 0x03, ODT_REC, &ODObjs.o_6099_axis0HomingSpeeds, NULL},
    {0x609A, 0x01, ODT_VAR, &ODObjs.o_609A_axis0HomingAcceleration, NULL},
    {0x60FF, 0x01, ODT_VAR, &ODObjs.o_60FF_axis0TargetVelocity, NULL},
    {0x6502, 0x01, ODT_VAR, &ODObjs.o_6502_axis0SupportedDriveModes, NULL},
    {0x683F, 0x01, ODT_VAR, &ODObjs.o_683F_axis1ErrorCode, NULL},
    {0x6840, 0x01, ODT_VAR, &ODObjs.o_6840_axis1Controlword, NULL},
    {0x6841, 0x01, ODT_VAR, &ODObjs.o_6841_axis1Statusword, NULL},
    {0x6860, 0x01, ODT_VAR, &ODObjs.o_6860_axis1ModesOfOperation, NULL},
    {0x6861, 0x01, ODT_VAR, &ODObjs.o_6861_axis1ModesOfOperationDisplay, NULL},
    {0x6864, 0x01, ODT_VAR, &ODObjs.o_6864_axis1PositionActualValue, NULL},
    {0x686C, 0x01, ODT_VAR, &ODObjs.o_686C_axis1VelocityActualValue, NULL},
    {0x687A, 0x01, ODT_VAR, &ODObjs.o_687A_axis1TargetPosition, NULL},
    {0x687C, 0x01, ODT_VAR, &ODObjs.o_687C_axis1HomeOffset, NULL},
    {0x6881, 0x01, ODT_VAR, &ODObjs.o_6881_axis1ProfileVelocity, NULL},
    {0x6883, 0x01, ODT_VAR, &ODObjs.o_6883_axis1ProfileAcceleration, NULL},
    {0x6884, 0x01, ODT_VAR, &ODObjs.o_6884_axis1ProfileDeceleration, NULL},
    {0x6885, 0x01, ODT_VAR, &ODObjs.o_6885_axis1QuickStopDeceleration, NULL},
    {0x6886, 0x01, ODT_VAR, &ODObjs.o_6886_axis1MotionProfileType, NULL},
    {0x6898, 0x01, ODT_VAR, &ODObjs.o_6898_axis1HomingMethod, NULL},
    {0x6899, 0x03, ODT_REC, &ODObjs.o_6899_axis1HomingSpeeds, NULL},
    {0x689A, 0x01, ODT_VAR, &ODObjs.o_689A_axis1HomingAcceleration, NULL},
    {0x68FF, 0x01, ODT_VAR, &ODObjs.o_68FF_axis1TargetVelocity, NULL},
    {0x6D02, 0x01, ODT_VAR, &ODObjs.o_6D02_axis1SupportedDriveModes, NULL},
    {0x703F, 0x01, ODT_VAR, &ODObjs.o_703F_axis2ErrorCode, NULL},
    {0x7040, 0x01, ODT_VAR, &ODObjs.o_7040_axis2Controlword, NULL},
    {0x7041, 0x01, ODT_VAR, &ODObjs.o_7041_axis2Statusword, NULL},
    {0x7060, 0x01, ODT_VAR, &ODObjs.o_7060_axis2ModesOfOperation, NULL},
    {0x7061, 0x01, ODT_VAR, &ODObjs.o_7061_axis2ModesOfOperationDisplay, NULL},
    {0x7064, 0x01, ODT_VAR, &ODObjs.o_7064_axis2PositionActualValue, NULL},
    {0x706C, 0x01, ODT_VAR, &ODObjs.o_706C_axis2VelocityActualValue, NULL},
    {0x707A, 0x01, ODT_VAR, &ODObjs.o_707A_axis2TargetPosition, NULL},
    {0x707C, 0x01, ODT_VAR, &ODObjs.o_707C_axis2HomeOffset, NULL},
    {0x7081, 0x01, ODT_VAR, &ODObjs.o_7081_axis2ProfileVelocity, NULL},
    {0x7083, 0x01, ODT_VAR, &ODObjs.o_7083_axis2ProfileAcceleration, NULL},
    {0x7084, 0x01, ODT_VAR, &ODObjs.o_7084_axis2ProfileDeceleration, NULL},
    {0x7085, 0x01, ODT_VAR, &ODObjs.o_7085_axis2QuickStopDeceleration, NULL},
    {0x7086, 0x01, ODT_VAR, &ODObjs.o_7086_axis2MotionProfileType, NULL},
    {0x7098, 0x01, ODT_VAR, &ODObjs.o_7098_axis2HomingMethod, NULL},
    {0x7099, 0x03, ODT_REC, &ODObjs.o_7099_axis2HomingSpeeds, NULL},
    {0x709A, 0x01, ODT_VAR, &ODObjs.o_709A_axis2HomingAcceleration, NULL},
    {0x70FF, 0x01, ODT_VAR, &ODObjs.o_70FF_axis2TargetVelocity, NULL},
    {0x7502, 0x01, ODT_VAR, &ODObjs.o_7502_axis2SupportedDriveModes, NULL},
    {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _OD = {
    (sizeof(ODList) / sizeof(ODList[0])) - 1,
    &ODList[0]
};

OD_t *OD = &_OD;
