/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: project.xdd
        File Version: 1.0.0

        Created:      2026/7/6 14:52:30
        Created By:   wdfk-prog
        Modified:     2026/9/1 21:12:33
        Modified By:  wdfk-prog

    Device Info:
        Vendor Name:  canopennode-rtt
        Vendor ID:    0x00000000
        Product Name: RT-Thread CANopenNode Demo Device
        Product ID:   0x00000001

        Description:  CANopenNode demo device for RT-Thread
*******************************************************************************/

#ifndef OD_H
#define OD_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define OD_CNT_NMT 1
#define OD_CNT_EM 1
#define OD_CNT_SYNC 1
#define OD_CNT_SYNC_PROD 1
#define OD_CNT_STORAGE 1
#define OD_CNT_TIME 1
#define OD_CNT_EM_PROD 1
#define OD_CNT_HB_CONS 1
#define OD_CNT_HB_PROD 1
#define OD_CNT_SDO_SRV 1
#define OD_CNT_SDO_CLI 1
#define OD_CNT_GFC 1
#define OD_CNT_SRDO 2
#define OD_CNT_RPDO 4
#define OD_CNT_TPDO 5


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define OD_CNT_ARR_1003 16
#define OD_CNT_ARR_1010 4
#define OD_CNT_ARR_1011 4
#define OD_CNT_ARR_1016 8
#define OD_CNT_ARR_13FF 2


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint32_t x1005_COB_ID_SYNCMessage;
    uint32_t x1006_communicationCyclePeriod;
    uint32_t x1007_synchronousWindowLength;
    char x1008_manufacturerDeviceName[9];
    char x1009_manufacturerHardwareVersion[7];
    char x100A_manufacturerSoftwareVersion[9];
    uint32_t x1012_COB_IDTimeStampObject;
    uint32_t x1014_COB_ID_EMCY;
    uint16_t x1015_inhibitTimeEMCY;
    uint8_t x1016_consumerHeartbeatTime_sub0;
    uint32_t x1016_consumerHeartbeatTime[OD_CNT_ARR_1016];
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t vendor_ID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identity;
    uint8_t x1019_synchronousCounterOverflowValue;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerTx;
        uint32_t COB_IDServerToClientRx;
        uint8_t node_IDOfTheSDOServer;
    } x1280_SDOClientParameter;
    uint8_t x1300_globalFail_safeCommandParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint8_t informationDirection;
        uint16_t safetyCycleTime;
        uint8_t safetyRelatedValidationTime;
        uint8_t transmissionType;
        uint32_t COB_ID1Normal;
        uint32_t COB_ID2Inverted;
    } x1301_SRDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint8_t informationDirection;
        uint16_t safetyCycleTime;
        uint8_t safetyRelatedValidationTime;
        uint8_t transmissionType;
        uint32_t COB_ID1Normal;
        uint32_t COB_ID2Inverted;
    } x1302_SRDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInSRDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
    } x1381_SRDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInSRDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
    } x1382_SRDOMappingParameter;
    uint8_t x13FE_SRDOConfigurationValid;
    uint8_t x13FF_SRDOChecksum_sub0;
    uint16_t x13FF_SRDOChecksum[OD_CNT_ARR_13FF];
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1400_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1401_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1402_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1403_RPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1600_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1601_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1602_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1603_RPDOMappingParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1800_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1801_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1802_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1803_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1804_TPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A00_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A01_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A02_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A03_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A04_TPDOMappingParameter;
} OD_PERSIST_COMM_t;

typedef struct {
    uint8_t x1001_errorRegister;
    uint32_t x1002_manufacturerStatusRegister;
    uint8_t x1010_storeParameters_sub0;
    uint32_t x1010_storeParameters[OD_CNT_ARR_1010];
    uint8_t x1011_restoreDefaultParameters_sub0;
    uint32_t x1011_restoreDefaultParameters[OD_CNT_ARR_1011];
    uint32_t x1013_highResolutionTimeStamp;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerRx;
        uint32_t COB_IDServerToClientTx;
    } x1200_SDOServerParameter;
    uint32_t x2100_status_value;
    uint32_t x2101_counter_value;
    uint32_t x2200_control_value;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t valid_time_rx_count;
        uint32_t applied_time_ms;
        uint16_t applied_time_days;
    } x2300_time_consumer_diagnostic;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t remote_rx_count;
        uint8_t last_source_node_id;
        uint16_t last_cob_id;
        uint16_t last_error_code;
        uint8_t last_error_register;
        uint8_t last_error_bit;
        uint32_t last_info_code;
    } x2301_emcy_consumer_diagnostic;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t rx_count;
        uint8_t safe_requested;
        uint32_t producer_request_seq;
        uint32_t producer_complete_seq;
        int32_t producer_result;
    } x2302_gfc_diagnostic;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t request_seq;
        uint8_t command;
        uint8_t remote_node;
        uint16_t index;
        uint8_t sub_index;
        uint32_t payload_size;
        uint32_t probe_value;
        uint8_t flags;
        uint32_t active_seq;
        uint32_t complete_seq;
        int32_t result;
        uint32_t abort_code;
        uint32_t transferred_size;
        uint32_t result_value;
        uint32_t checksum;
    } x2303_sdo_client_test;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t request_seq;
        uint8_t command;
        uint8_t entry_sub_index;
        uint32_t raw_offset;
        uint8_t raw_size;
        uint32_t raw_value;
        uint32_t active_seq;
        uint32_t complete_seq;
        int32_t result;
        uint8_t startup_state;
        int32_t startup_result;
        uint32_t startup_error;
        uint32_t storage_offset;
        uint32_t eeprom_size;
        uint16_t page_size;
        uint8_t addr_input;
        uint32_t signature_address;
        uint32_t data_address;
        uint32_t data_length;
        uint32_t raw_start;
        uint32_t raw_length;
        uint32_t signature_value;
        uint8_t backup_valid;
        uint16_t backup_crc;
        uint32_t startup_seq;
        uint16_t startup_probe;
    } x2305_storage_diagnostic;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t rx_normal;
        uint32_t rx_inverted;
        uint32_t tx_normal;
        uint32_t tx_inverted;
        int8_t aggregate_state;
        int8_t rx_state;
        int8_t tx_state;
        uint32_t state_seq;
        uint32_t tx_request_seq;
        uint32_t tx_complete_seq;
        int32_t tx_request_result;
    } x2306_srdo_diagnostic;
    uint16_t x603F_axis0ErrorCode;
    uint16_t x6040_axis0Controlword;
    uint16_t x6041_axis0Statusword;
    int8_t x6060_axis0ModesOfOperation;
    int8_t x6061_axis0ModesOfOperationDisplay;
    int32_t x6064_axis0PositionActualValue;
    int32_t x606C_axis0VelocityActualValue;
    int16_t x6071_axis0TargetTorque;
    int16_t x6077_axis0TorqueActualValue;
    int32_t x607A_axis0TargetPosition;
    int32_t x607C_axis0HomeOffset;
    uint32_t x6081_axis0ProfileVelocity;
    uint32_t x6083_axis0ProfileAcceleration;
    uint32_t x6084_axis0ProfileDeceleration;
    uint32_t x6085_axis0QuickStopDeceleration;
    int16_t x6086_axis0MotionProfileType;
    int8_t x6098_axis0HomingMethod;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t speedDuringSearchForSwitch;
        uint32_t speedDuringSearchForZero;
    } x6099_axis0HomingSpeeds;
    uint32_t x609A_axis0HomingAcceleration;
    int32_t x60FF_axis0TargetVelocity;
    uint32_t x6502_axis0SupportedDriveModes;
    uint16_t x683F_axis1ErrorCode;
    uint16_t x6840_axis1Controlword;
    uint16_t x6841_axis1Statusword;
    int8_t x6860_axis1ModesOfOperation;
    int8_t x6861_axis1ModesOfOperationDisplay;
    int32_t x6864_axis1PositionActualValue;
    int32_t x686C_axis1VelocityActualValue;
    int16_t x6871_axis1TargetTorque;
    int16_t x6877_axis1TorqueActualValue;
    int32_t x687A_axis1TargetPosition;
    int32_t x687C_axis1HomeOffset;
    uint32_t x6881_axis1ProfileVelocity;
    uint32_t x6883_axis1ProfileAcceleration;
    uint32_t x6884_axis1ProfileDeceleration;
    uint32_t x6885_axis1QuickStopDeceleration;
    int16_t x6886_axis1MotionProfileType;
    int8_t x6898_axis1HomingMethod;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t speedDuringSearchForSwitch;
        uint32_t speedDuringSearchForZero;
    } x6899_axis1HomingSpeeds;
    uint32_t x689A_axis1HomingAcceleration;
    int32_t x68FF_axis1TargetVelocity;
    uint32_t x6D02_axis1SupportedDriveModes;
    uint16_t x703F_axis2ErrorCode;
    uint16_t x7040_axis2Controlword;
    uint16_t x7041_axis2Statusword;
    int8_t x7060_axis2ModesOfOperation;
    int8_t x7061_axis2ModesOfOperationDisplay;
    int32_t x7064_axis2PositionActualValue;
    int32_t x706C_axis2VelocityActualValue;
    int16_t x7071_axis2TargetTorque;
    int16_t x7077_axis2TorqueActualValue;
    int32_t x707A_axis2TargetPosition;
    int32_t x707C_axis2HomeOffset;
    uint32_t x7081_axis2ProfileVelocity;
    uint32_t x7083_axis2ProfileAcceleration;
    uint32_t x7084_axis2ProfileDeceleration;
    uint32_t x7085_axis2QuickStopDeceleration;
    int16_t x7086_axis2MotionProfileType;
    int8_t x7098_axis2HomingMethod;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t speedDuringSearchForSwitch;
        uint32_t speedDuringSearchForZero;
    } x7099_axis2HomingSpeeds;
    uint32_t x709A_axis2HomingAcceleration;
    int32_t x70FF_axis2TargetVelocity;
    uint32_t x7502_axis2SupportedDriveModes;
} OD_RAM_t;

#ifndef OD_ATTR_PERSIST_COMM
#define OD_ATTR_PERSIST_COMM
#endif
extern OD_ATTR_PERSIST_COMM OD_PERSIST_COMM_t OD_PERSIST_COMM;

#ifndef OD_ATTR_RAM
#define OD_ATTR_RAM
#endif
extern OD_ATTR_RAM OD_RAM_t OD_RAM;

#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
extern OD_ATTR_OD OD_t *OD;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define OD_ENTRY_H1000 &OD->list[0]
#define OD_ENTRY_H1001 &OD->list[1]
#define OD_ENTRY_H1002 &OD->list[2]
#define OD_ENTRY_H1003 &OD->list[3]
#define OD_ENTRY_H1005 &OD->list[4]
#define OD_ENTRY_H1006 &OD->list[5]
#define OD_ENTRY_H1007 &OD->list[6]
#define OD_ENTRY_H1008 &OD->list[7]
#define OD_ENTRY_H1009 &OD->list[8]
#define OD_ENTRY_H100A &OD->list[9]
#define OD_ENTRY_H1010 &OD->list[10]
#define OD_ENTRY_H1011 &OD->list[11]
#define OD_ENTRY_H1012 &OD->list[12]
#define OD_ENTRY_H1013 &OD->list[13]
#define OD_ENTRY_H1014 &OD->list[14]
#define OD_ENTRY_H1015 &OD->list[15]
#define OD_ENTRY_H1016 &OD->list[16]
#define OD_ENTRY_H1017 &OD->list[17]
#define OD_ENTRY_H1018 &OD->list[18]
#define OD_ENTRY_H1019 &OD->list[19]
#define OD_ENTRY_H1200 &OD->list[20]
#define OD_ENTRY_H1280 &OD->list[21]
#define OD_ENTRY_H1300 &OD->list[22]
#define OD_ENTRY_H1301 &OD->list[23]
#define OD_ENTRY_H1302 &OD->list[24]
#define OD_ENTRY_H1381 &OD->list[25]
#define OD_ENTRY_H1382 &OD->list[26]
#define OD_ENTRY_H13FE &OD->list[27]
#define OD_ENTRY_H13FF &OD->list[28]
#define OD_ENTRY_H1400 &OD->list[29]
#define OD_ENTRY_H1401 &OD->list[30]
#define OD_ENTRY_H1402 &OD->list[31]
#define OD_ENTRY_H1403 &OD->list[32]
#define OD_ENTRY_H1600 &OD->list[33]
#define OD_ENTRY_H1601 &OD->list[34]
#define OD_ENTRY_H1602 &OD->list[35]
#define OD_ENTRY_H1603 &OD->list[36]
#define OD_ENTRY_H1800 &OD->list[37]
#define OD_ENTRY_H1801 &OD->list[38]
#define OD_ENTRY_H1802 &OD->list[39]
#define OD_ENTRY_H1803 &OD->list[40]
#define OD_ENTRY_H1804 &OD->list[41]
#define OD_ENTRY_H1A00 &OD->list[42]
#define OD_ENTRY_H1A01 &OD->list[43]
#define OD_ENTRY_H1A02 &OD->list[44]
#define OD_ENTRY_H1A03 &OD->list[45]
#define OD_ENTRY_H1A04 &OD->list[46]
#define OD_ENTRY_H2100 &OD->list[47]
#define OD_ENTRY_H2101 &OD->list[48]
#define OD_ENTRY_H2200 &OD->list[49]
#define OD_ENTRY_H2300 &OD->list[50]
#define OD_ENTRY_H2301 &OD->list[51]
#define OD_ENTRY_H2302 &OD->list[52]
#define OD_ENTRY_H2303 &OD->list[53]
#define OD_ENTRY_H2304 &OD->list[54]
#define OD_ENTRY_H2305 &OD->list[55]
#define OD_ENTRY_H2306 &OD->list[56]
#define OD_ENTRY_H603F &OD->list[57]
#define OD_ENTRY_H6040 &OD->list[58]
#define OD_ENTRY_H6041 &OD->list[59]
#define OD_ENTRY_H6060 &OD->list[60]
#define OD_ENTRY_H6061 &OD->list[61]
#define OD_ENTRY_H6064 &OD->list[62]
#define OD_ENTRY_H606C &OD->list[63]
#define OD_ENTRY_H6071 &OD->list[64]
#define OD_ENTRY_H6077 &OD->list[65]
#define OD_ENTRY_H607A &OD->list[66]
#define OD_ENTRY_H607C &OD->list[67]
#define OD_ENTRY_H6081 &OD->list[68]
#define OD_ENTRY_H6083 &OD->list[69]
#define OD_ENTRY_H6084 &OD->list[70]
#define OD_ENTRY_H6085 &OD->list[71]
#define OD_ENTRY_H6086 &OD->list[72]
#define OD_ENTRY_H6098 &OD->list[73]
#define OD_ENTRY_H6099 &OD->list[74]
#define OD_ENTRY_H609A &OD->list[75]
#define OD_ENTRY_H60FF &OD->list[76]
#define OD_ENTRY_H6502 &OD->list[77]
#define OD_ENTRY_H683F &OD->list[78]
#define OD_ENTRY_H6840 &OD->list[79]
#define OD_ENTRY_H6841 &OD->list[80]
#define OD_ENTRY_H6860 &OD->list[81]
#define OD_ENTRY_H6861 &OD->list[82]
#define OD_ENTRY_H6864 &OD->list[83]
#define OD_ENTRY_H686C &OD->list[84]
#define OD_ENTRY_H6871 &OD->list[85]
#define OD_ENTRY_H6877 &OD->list[86]
#define OD_ENTRY_H687A &OD->list[87]
#define OD_ENTRY_H687C &OD->list[88]
#define OD_ENTRY_H6881 &OD->list[89]
#define OD_ENTRY_H6883 &OD->list[90]
#define OD_ENTRY_H6884 &OD->list[91]
#define OD_ENTRY_H6885 &OD->list[92]
#define OD_ENTRY_H6886 &OD->list[93]
#define OD_ENTRY_H6898 &OD->list[94]
#define OD_ENTRY_H6899 &OD->list[95]
#define OD_ENTRY_H689A &OD->list[96]
#define OD_ENTRY_H68FF &OD->list[97]
#define OD_ENTRY_H6D02 &OD->list[98]
#define OD_ENTRY_H703F &OD->list[99]
#define OD_ENTRY_H7040 &OD->list[100]
#define OD_ENTRY_H7041 &OD->list[101]
#define OD_ENTRY_H7060 &OD->list[102]
#define OD_ENTRY_H7061 &OD->list[103]
#define OD_ENTRY_H7064 &OD->list[104]
#define OD_ENTRY_H706C &OD->list[105]
#define OD_ENTRY_H7071 &OD->list[106]
#define OD_ENTRY_H7077 &OD->list[107]
#define OD_ENTRY_H707A &OD->list[108]
#define OD_ENTRY_H707C &OD->list[109]
#define OD_ENTRY_H7081 &OD->list[110]
#define OD_ENTRY_H7083 &OD->list[111]
#define OD_ENTRY_H7084 &OD->list[112]
#define OD_ENTRY_H7085 &OD->list[113]
#define OD_ENTRY_H7086 &OD->list[114]
#define OD_ENTRY_H7098 &OD->list[115]
#define OD_ENTRY_H7099 &OD->list[116]
#define OD_ENTRY_H709A &OD->list[117]
#define OD_ENTRY_H70FF &OD->list[118]
#define OD_ENTRY_H7502 &OD->list[119]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define OD_ENTRY_H1000_deviceType &OD->list[0]
#define OD_ENTRY_H1001_errorRegister &OD->list[1]
#define OD_ENTRY_H1002_manufacturerStatusRegister &OD->list[2]
#define OD_ENTRY_H1003_pre_definedErrorField &OD->list[3]
#define OD_ENTRY_H1005_COB_ID_SYNCMessage &OD->list[4]
#define OD_ENTRY_H1006_communicationCyclePeriod &OD->list[5]
#define OD_ENTRY_H1007_synchronousWindowLength &OD->list[6]
#define OD_ENTRY_H1008_manufacturerDeviceName &OD->list[7]
#define OD_ENTRY_H1009_manufacturerHardwareVersion &OD->list[8]
#define OD_ENTRY_H100A_manufacturerSoftwareVersion &OD->list[9]
#define OD_ENTRY_H1010_storeParameters &OD->list[10]
#define OD_ENTRY_H1011_restoreDefaultParameters &OD->list[11]
#define OD_ENTRY_H1012_COB_IDTimeStampObject &OD->list[12]
#define OD_ENTRY_H1013_highResolutionTimeStamp &OD->list[13]
#define OD_ENTRY_H1014_COB_ID_EMCY &OD->list[14]
#define OD_ENTRY_H1015_inhibitTimeEMCY &OD->list[15]
#define OD_ENTRY_H1016_consumerHeartbeatTime &OD->list[16]
#define OD_ENTRY_H1017_producerHeartbeatTime &OD->list[17]
#define OD_ENTRY_H1018_identity &OD->list[18]
#define OD_ENTRY_H1019_synchronousCounterOverflowValue &OD->list[19]
#define OD_ENTRY_H1200_SDOServerParameter &OD->list[20]
#define OD_ENTRY_H1280_SDOClientParameter &OD->list[21]
#define OD_ENTRY_H1300_globalFail_safeCommandParameter &OD->list[22]
#define OD_ENTRY_H1301_SRDOCommunicationParameter &OD->list[23]
#define OD_ENTRY_H1302_SRDOCommunicationParameter &OD->list[24]
#define OD_ENTRY_H1381_SRDOMappingParameter &OD->list[25]
#define OD_ENTRY_H1382_SRDOMappingParameter &OD->list[26]
#define OD_ENTRY_H13FE_SRDOConfigurationValid &OD->list[27]
#define OD_ENTRY_H13FF_SRDOChecksum &OD->list[28]
#define OD_ENTRY_H1400_RPDOCommunicationParameter &OD->list[29]
#define OD_ENTRY_H1401_RPDOCommunicationParameter &OD->list[30]
#define OD_ENTRY_H1402_RPDOCommunicationParameter &OD->list[31]
#define OD_ENTRY_H1403_RPDOCommunicationParameter &OD->list[32]
#define OD_ENTRY_H1600_RPDOMappingParameter &OD->list[33]
#define OD_ENTRY_H1601_RPDOMappingParameter &OD->list[34]
#define OD_ENTRY_H1602_RPDOMappingParameter &OD->list[35]
#define OD_ENTRY_H1603_RPDOMappingParameter &OD->list[36]
#define OD_ENTRY_H1800_TPDOCommunicationParameter &OD->list[37]
#define OD_ENTRY_H1801_TPDOCommunicationParameter &OD->list[38]
#define OD_ENTRY_H1802_TPDOCommunicationParameter &OD->list[39]
#define OD_ENTRY_H1803_TPDOCommunicationParameter &OD->list[40]
#define OD_ENTRY_H1804_TPDOCommunicationParameter &OD->list[41]
#define OD_ENTRY_H1A00_TPDOMappingParameter &OD->list[42]
#define OD_ENTRY_H1A01_TPDOMappingParameter &OD->list[43]
#define OD_ENTRY_H1A02_TPDOMappingParameter &OD->list[44]
#define OD_ENTRY_H1A03_TPDOMappingParameter &OD->list[45]
#define OD_ENTRY_H1A04_TPDOMappingParameter &OD->list[46]
#define OD_ENTRY_H2100_status_value &OD->list[47]
#define OD_ENTRY_H2101_counter_value &OD->list[48]
#define OD_ENTRY_H2200_control_value &OD->list[49]
#define OD_ENTRY_H2300_time_consumer_diagnostic &OD->list[50]
#define OD_ENTRY_H2301_emcy_consumer_diagnostic &OD->list[51]
#define OD_ENTRY_H2302_gfc_diagnostic &OD->list[52]
#define OD_ENTRY_H2303_sdo_client_test &OD->list[53]
#define OD_ENTRY_H2304_sdo_server_block_test &OD->list[54]
#define OD_ENTRY_H2305_storage_diagnostic &OD->list[55]
#define OD_ENTRY_H2306_srdo_diagnostic &OD->list[56]
#define OD_ENTRY_H603F_axis0ErrorCode &OD->list[57]
#define OD_ENTRY_H6040_axis0Controlword &OD->list[58]
#define OD_ENTRY_H6041_axis0Statusword &OD->list[59]
#define OD_ENTRY_H6060_axis0ModesOfOperation &OD->list[60]
#define OD_ENTRY_H6061_axis0ModesOfOperationDisplay &OD->list[61]
#define OD_ENTRY_H6064_axis0PositionActualValue &OD->list[62]
#define OD_ENTRY_H606C_axis0VelocityActualValue &OD->list[63]
#define OD_ENTRY_H6071_axis0TargetTorque &OD->list[64]
#define OD_ENTRY_H6077_axis0TorqueActualValue &OD->list[65]
#define OD_ENTRY_H607A_axis0TargetPosition &OD->list[66]
#define OD_ENTRY_H607C_axis0HomeOffset &OD->list[67]
#define OD_ENTRY_H6081_axis0ProfileVelocity &OD->list[68]
#define OD_ENTRY_H6083_axis0ProfileAcceleration &OD->list[69]
#define OD_ENTRY_H6084_axis0ProfileDeceleration &OD->list[70]
#define OD_ENTRY_H6085_axis0QuickStopDeceleration &OD->list[71]
#define OD_ENTRY_H6086_axis0MotionProfileType &OD->list[72]
#define OD_ENTRY_H6098_axis0HomingMethod &OD->list[73]
#define OD_ENTRY_H6099_axis0HomingSpeeds &OD->list[74]
#define OD_ENTRY_H609A_axis0HomingAcceleration &OD->list[75]
#define OD_ENTRY_H60FF_axis0TargetVelocity &OD->list[76]
#define OD_ENTRY_H6502_axis0SupportedDriveModes &OD->list[77]
#define OD_ENTRY_H683F_axis1ErrorCode &OD->list[78]
#define OD_ENTRY_H6840_axis1Controlword &OD->list[79]
#define OD_ENTRY_H6841_axis1Statusword &OD->list[80]
#define OD_ENTRY_H6860_axis1ModesOfOperation &OD->list[81]
#define OD_ENTRY_H6861_axis1ModesOfOperationDisplay &OD->list[82]
#define OD_ENTRY_H6864_axis1PositionActualValue &OD->list[83]
#define OD_ENTRY_H686C_axis1VelocityActualValue &OD->list[84]
#define OD_ENTRY_H6871_axis1TargetTorque &OD->list[85]
#define OD_ENTRY_H6877_axis1TorqueActualValue &OD->list[86]
#define OD_ENTRY_H687A_axis1TargetPosition &OD->list[87]
#define OD_ENTRY_H687C_axis1HomeOffset &OD->list[88]
#define OD_ENTRY_H6881_axis1ProfileVelocity &OD->list[89]
#define OD_ENTRY_H6883_axis1ProfileAcceleration &OD->list[90]
#define OD_ENTRY_H6884_axis1ProfileDeceleration &OD->list[91]
#define OD_ENTRY_H6885_axis1QuickStopDeceleration &OD->list[92]
#define OD_ENTRY_H6886_axis1MotionProfileType &OD->list[93]
#define OD_ENTRY_H6898_axis1HomingMethod &OD->list[94]
#define OD_ENTRY_H6899_axis1HomingSpeeds &OD->list[95]
#define OD_ENTRY_H689A_axis1HomingAcceleration &OD->list[96]
#define OD_ENTRY_H68FF_axis1TargetVelocity &OD->list[97]
#define OD_ENTRY_H6D02_axis1SupportedDriveModes &OD->list[98]
#define OD_ENTRY_H703F_axis2ErrorCode &OD->list[99]
#define OD_ENTRY_H7040_axis2Controlword &OD->list[100]
#define OD_ENTRY_H7041_axis2Statusword &OD->list[101]
#define OD_ENTRY_H7060_axis2ModesOfOperation &OD->list[102]
#define OD_ENTRY_H7061_axis2ModesOfOperationDisplay &OD->list[103]
#define OD_ENTRY_H7064_axis2PositionActualValue &OD->list[104]
#define OD_ENTRY_H706C_axis2VelocityActualValue &OD->list[105]
#define OD_ENTRY_H7071_axis2TargetTorque &OD->list[106]
#define OD_ENTRY_H7077_axis2TorqueActualValue &OD->list[107]
#define OD_ENTRY_H707A_axis2TargetPosition &OD->list[108]
#define OD_ENTRY_H707C_axis2HomeOffset &OD->list[109]
#define OD_ENTRY_H7081_axis2ProfileVelocity &OD->list[110]
#define OD_ENTRY_H7083_axis2ProfileAcceleration &OD->list[111]
#define OD_ENTRY_H7084_axis2ProfileDeceleration &OD->list[112]
#define OD_ENTRY_H7085_axis2QuickStopDeceleration &OD->list[113]
#define OD_ENTRY_H7086_axis2MotionProfileType &OD->list[114]
#define OD_ENTRY_H7098_axis2HomingMethod &OD->list[115]
#define OD_ENTRY_H7099_axis2HomingSpeeds &OD->list[116]
#define OD_ENTRY_H709A_axis2HomingAcceleration &OD->list[117]
#define OD_ENTRY_H70FF_axis2TargetVelocity &OD->list[118]
#define OD_ENTRY_H7502_axis2SupportedDriveModes &OD->list[119]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define OD_INIT_CONFIG(config) {\
    (config).CNT_NMT = OD_CNT_NMT;\
    (config).ENTRY_H1017 = OD_ENTRY_H1017;\
    (config).CNT_HB_CONS = OD_CNT_HB_CONS;\
    (config).CNT_ARR_1016 = OD_CNT_ARR_1016;\
    (config).ENTRY_H1016 = OD_ENTRY_H1016;\
    (config).CNT_EM = OD_CNT_EM;\
    (config).ENTRY_H1001 = OD_ENTRY_H1001;\
    (config).ENTRY_H1014 = OD_ENTRY_H1014;\
    (config).ENTRY_H1015 = OD_ENTRY_H1015;\
    (config).CNT_ARR_1003 = OD_CNT_ARR_1003;\
    (config).ENTRY_H1003 = OD_ENTRY_H1003;\
    (config).CNT_SDO_SRV = OD_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = OD_ENTRY_H1200;\
    (config).CNT_SDO_CLI = OD_CNT_SDO_CLI;\
    (config).ENTRY_H1280 = OD_ENTRY_H1280;\
    (config).CNT_TIME = OD_CNT_TIME;\
    (config).ENTRY_H1012 = OD_ENTRY_H1012;\
    (config).CNT_SYNC = OD_CNT_SYNC;\
    (config).ENTRY_H1005 = OD_ENTRY_H1005;\
    (config).ENTRY_H1006 = OD_ENTRY_H1006;\
    (config).ENTRY_H1007 = OD_ENTRY_H1007;\
    (config).ENTRY_H1019 = OD_ENTRY_H1019;\
    (config).CNT_RPDO = OD_CNT_RPDO;\
    (config).ENTRY_H1400 = OD_ENTRY_H1400;\
    (config).ENTRY_H1600 = OD_ENTRY_H1600;\
    (config).CNT_TPDO = OD_CNT_TPDO;\
    (config).ENTRY_H1800 = OD_ENTRY_H1800;\
    (config).ENTRY_H1A00 = OD_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = OD_CNT_GFC;\
    (config).ENTRY_H1300 = OD_ENTRY_H1300;\
    (config).CNT_SRDO = OD_CNT_SRDO;\
    (config).ENTRY_H1301 = OD_ENTRY_H1301;\
    (config).ENTRY_H1381 = OD_ENTRY_H1381;\
    (config).ENTRY_H13FE = OD_ENTRY_H13FE;\
    (config).ENTRY_H13FF = OD_ENTRY_H13FF;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* OD_H */
